### ISSUE TITLE
Ability to print cards to A4 sheets

### ISSUE THREAD

**Issue by evolve2k** [andymeneely/squib#100]
I'm wanting to build out our game as a print-and-play card game initially.
By default the system generates each card into it's own image file. 

Please include a way to generate the cards onto A4 sized sheets containing a number of cards on one sheet. This way the game would be easier to make available as a number of sheets that users can just download/print & cut-out.

Thanks for this awesome tool!

**Comment by andymeneely** [comment]
Check out the `save_pdf` method (http://andymeneely.github.io/squib/doc/frames.html#!file.README.html). You can specify the dimensions of the paper directly, so any paper size will work.

**Comment by evolve2k** [comment]
Thanks heaps for the help and quick response.

For anyone following my trail, I managed to get out what I wanted with this:

    save_pdf file: 'cards.pdf',
		        width: "8.27in", height: "11.69in", 
		        margin: 75, gap: 5, trim: 37
