### ISSUE TITLE
Easy way to detect number of cards in CSV file rather than stating it directly.

### ISSUE THREAD

**Issue by evolve2k** [andymeneely/squib#101]
The example files use this structure..

    Squib::Deck.new(cards: 12, layout: %w(hand.yml layout.yml)) do

I'm wanting to have Squib just know how many records are in my table and to be able to use that as the cards value (instead of say the '12' in the example above). 

Is this possible?

**Comment by andymeneely** [comment]
Yep! I usually make my csv or xlsx call outside the `Squib::Deck` call, then pick a column for its size. like this:

```ruby
data = Squib.csv file: 'deck.csv'
Squib::Deck.new(cards: data['Title'].size) do
end
```

As a side note: we should probably keep GitHub issues for bugs and feature requests. For support questions, I'm also tracking StackOverflow questions with the tags "squib" and "ruby".

**Comment by evolve2k** [comment]
Cheers I was wondering where to put my questions, I'll move them across here.
Thanks for your friendly support. Really really appreciate this project!!!!

**Comment by andymeneely** [comment]
Absolutely! Glad you're liking it.
