### ISSUE TITLE
Stroke-and-fill as an option in addition to Fill-and-stroke (for text)

### ISSUE THREAD

**Issue by pickfifteen** [andymeneely/squib#102]
I have a card design with an extremely thick stroke on certain text. The existing fill-and-stroke does not provide the correct look that the former stroke-and-fill option does; with a very thick stroke, the fill-and-stroke method causes the text to begin to disappear behind the stroke.

**Comment by andymeneely** [comment]
What about shrinking your `stroke-width`?

**Comment by pickfifteen** [comment]
It doesn't seem to be possible to get this look just by adjusting the stroke width. This image is from the previous method which stroked first and then filled. 
![stroke](https://cloud.githubusercontent.com/assets/8549883/8922254/8a35bdea-34ae-11e5-8fe7-e75da15e303b.png)

**Comment by andymeneely** [comment]
Makes sense. I'll add an option now.

**Comment by andymeneely** [comment]
Ok try this on for size: 19767c54c4cdb208517b52d665ee23f7d6a7d91a

**Comment by pickfifteen** [comment]
Have a vertical alignment bug, image attached. The stroke is in the correct place, the fill is off. I was able to get it in the right place by reusing the two lines involving `vertical_start` again but I'm not sure if that's the correct way to fix it. 

![stroke2](https://cloud.githubusercontent.com/assets/8549883/8922638/8d4996d2-34b3-11e5-9f6c-e7be2edd98b2.png)

**Comment by andymeneely** [comment]
Ah - right. Try this one: fed2889aefaa184e1be04cf8f006d25d2c633820

**Comment by pickfifteen** [comment]
That looks great. This fixes a showstopping problem with my workaround that I couldn't resolve and cleans things up a lot, thanks!
