### ISSUE TITLE
Allow basic transformation of loaded images

### ISSUE THREAD

**Issue by andymeneely** [andymeneely/squib#11]
Allow for rotation, skew, and flip of both pngs and loaded images. Basic Cairo transformations on the surface, just like resizing.

**Comment by bcompter** [comment]
How about cropping too?  It would be handle when using sprite sheets or just changing the look/perspective of a background image.

**Comment by andymeneely** [comment]
Yep cropping can be done too. Hadn't thought of the sprite sheet workflow, but that makes sense.

**Comment by bcompter** [comment]
Awesome!  Great work.  Did not expect that so fast!

**Comment by andymeneely** [comment]
Sure - it's not in the v0.8 release. If you want to help me test it out, you can set your Gemfile to my master branch (http://andymeneely.github.io/squib/doc/file.README.html#Testing_Pre-Builds).

**Comment by bcompter** [comment]
I have just the project in mind for this.  Hopefully I'll have a few spare clock cycles this weekend!
