### ISSUE TITLE
Better documentation ideas

### ISSUE THREAD

**Issue by andymeneely** [andymeneely/squib#110]
There are lot of things I'd like to do better to make learning Squib easier. Let's talk about those here.

**Comment by andymeneely** [comment]
Here's a comment from a BGG GeekMail I got from Joe that started this off:

Hi there. I just started checking out squib, and it's quite awesome! I'll probably use it in all of my games that use cards from now on. I'm a Ruby programmer myself, so it's right up my alley. It's quite a nice, elegant DSL that I think can definitely be used by all sorts, programmers and non-programmers alike.

That said, I've noticed a few points of difficulty with learning how to use it (just documentation issues... I think the design is pretty solid). Hopefully you're open to some ideas from someone with some experience with documentation and UI...

- The already-provided suite of examples is great, but to help all learning styles, I think it would be useful to have some part of the documentation (probably near the beginning, like in the Getting Started section) start with the [practical] bare minimum deck.rb (the one generated with 'squib new'). Explain the defaults that are in place to make that small file generate cards the way it does. Then slowly add more options, expanding what's being done step by step, until at the end a more complex deck is being generated.

- I think it would be immensely helpful to format the Instance Method Summary in the Deck API docs a bit differently. That list makes sense to programmers, but I think listing the return type before the name makes it rather confusing for the less-technical people. Also, it makes it hard to scan the list quickly, even for those not confused by the format of the list, since the method names are not aligned with one another due to being offset by the return types.

I believe these ideas would really help folks who are less familiar with Ruby (and programming in general), since the docs as they are now are fairly programmer-specific. Even just the formatting of the docs (especially the API docs) will likely read as technical gobbledygook to folks who do actually have the capacity to understand it but just aren't used to programming documentation. And it really is a simple enough DSL that they should be able to use it anyway.

I'm willing to help, by the way. I'll probably end up doing this stuff anyway, and posting it somewhere for reference. Perhaps a good solution would be to have separate set of docs for the less-technical users? I'm not really familiar with the documentation method you're using (is it Yard?) so I'm not sure how to make a separate set of docs, but if you point me in the right direction I'd love to fill it in.

Anyway, let me know. I'm up for chatting about it in general, about whether you think these are good ideas or not, about how I could help, etc etc. Also, if there's somewhere better to discuss this, let me know. I wasn't sure if this would be best in github issues or a squib thread on bgg, so i figured I'd message you first. If you want to take this to email, my email address is miragliuolo@gmail.com

Thanks for making such an awesome tool!
--Joe

**Comment by andymeneely** [comment]
And here was my response: 

Hi Joe,
I would LOVE help with documentation. I've been so swamped lately and I've been meaning to improve upon it.

In particular, I feel like we need more "Guides". Longform descriptions of things and how to walk through them so you don't just get a bunch of little examples, but more fully formed thinking about prototyping with automation. And tons of examples, of course.

Also, I would love to have documented examples projects where people can see the history. I've been working on a game (https://github.com/andymeneely/project-spider-monkey) where I prototyped 100% from the beginning in a small, incremental way so that individual commits can be inspected. A set of longform entries that really step you through that history is what I envision.

I was initially thinking that these guides and histories would be on a blog on the Squib website. I even started prototyping one, although contributing is a bit complicated since it involves building with Jekyll and pull request - so most non-Github folks would not been keen on that. Another option is the repo's wiki. It is technically open to the public and I had one guy contribute some random thing once. I would LOVE to see the wiki look like some of these https://github.com/showcases/projects-with-great-wikis

The instance method summary I think could be improved in form. I would like that documentation to stay in the style that it is in because, after all, if you're using Squib you ARE a programmer - so there needs to be technical, method-by-method documentation somewhere. But the format, yeah, I'm not a fan. And changing the Yard formatting is much more time consuming than it should be. I have yet to find a good replacement for stupid Yard that lets me compile my Ruby comments from source.

Screencasting would also be cool, although I haven't done much with that. That could get out of date quickly, though, and keeping things up to date is critical for documentation. Wrong documentation is worse than no documentation, imho.

**Comment by andymeneely** [comment]
By the way, one method for documentation could be something like Slate (https://github.com/tripit/slate), although it's backed by a GitHub repo so contributing is based on pull requests. Travis' documentation I think is Slate. http://docs.travis-ci.com/api/#builds

**Comment by andymeneely** [comment]
Or https://readthedocs.org/ is another place I've looked at.

**Comment by andymeneely** [comment]
At this point I'm leaning toward a community-oriented approach with the wiki. That has the disadvantage of not being as pretty or having nice Google analytics, but it means more people will edit it - which I think is most important.

Additionally, I've been playing with better ways of managing the samples. In particular, I'm going to start spinning them out to their own Gists, and then hooking them back into the original repository using Git submodules.

I'll be creating some issues on working for this: #119, #117 for starters

**Comment by andymeneely** [comment]
I made the decision to convert to readthedocs.org and maintain it there. There's just nothing that comes close to what they're doing, so I'm willing to bear that it's python.

It's definitely a work in progress, but the live link is http://squib.readthedocs.org

**Comment by bcompter** [comment]
I'm guessing anyone can contribute to these docs using pull requests to the docs folder?

**Comment by andymeneely** [comment]
Yup! It'll be through a pull request mechanism, but yep. This'll be a replacement for that yucky YARD website, so it'll be more of the "official" documentation. The wiki will be more for community documentation like recipes and tutorials.

**Comment by andymeneely** [comment]
I'm approaching the end of my port to readthedocs. I need to finish the opening tutorial, and correct/finish some of the DSL reference, and embed the samples in GitHub gists and embed them right in the docs (e.g. text). But the meat of it is there. Let me know what you think.   

http://squib.readthedocs.org 

When I'm done with that I'll go back to the wiki and pull out the tutorial and have it be a space for recipes. The README will be greatly simplified, and the landing page will still be what it is. No more YARD on rubydoc.info.
