### ISSUE TITLE
Add a way to suppress PNG scaling warning

### ISSUE THREAD

**Issue by programmingisgood** [andymeneely/squib#120]
This is more of a feature request than an issue but I am not entirely familiar with how GitHub works so please let me know if there is a better place for feature requests.

I would like a way to suppress this warning:

-0700 WARN: PNG scaling results in aliasing.

Thanks Andy!

**Comment by andymeneely** [comment]
Haha I *knew* someone would request this eventually. Yeah I'll add that into the next release.

(Yep! this is the place for feature requests!)
