### ISSUE TITLE
Mac OSX stroke text goes awry

### ISSUE THREAD

**Issue by andymeneely** [andymeneely/squib#121]
On the [BGG thread](https://boardgamegeek.com/article/20767299#20767299), Scrapyardarmory reported these happening on the `text_options.rb` sample.

![text_00](https://cloud.githubusercontent.com/assets/341847/10846388/c7169546-7ee5-11e5-8aa8-58e3df4cdbc4.png)

**Comment by andymeneely** [comment]
Ok, I have some questions: 
  * Are you using HomeBrew or some other package manager to get the native libraries? What version of Pango do you have?
  * Does this code produce wonky results?

```ruby
require 'pango'
require 'cairo'

surface = Cairo::ImageSurface.new(100,100)
cc = Cairo::Context.new(surface)
cc.set_source_color('white')
cc.paint

cc.set_source_color('black')
layout = cc.create_pango_layout
layout.font_description = Pango::FontDescription.new('Sans Bold 36')
layout.text = 'foo'
cc.show_pango_layout(layout)

cc.set_source_color('green')
cc.pango_layout_path(layout)
cc.set_line_width 3
cc.set_line_join Cairo::LINE_JOIN_ROUND
cc.set_line_cap Cairo::LINE_CAP_ROUND
cc.set_dash []
cc.stroke

surface.write_to_png('bug_121.png')
```
Mine (on Windows) looks like this:
![bug_121](https://cloud.githubusercontent.com/assets/341847/10846606/469bf54e-7ee7-11e5-8f4f-435298a86e57.png)

**Comment by bcompter** [comment]
Correct, I am using homebrew.

Pango version is pango-1.38.0.  Output png is attached.

![bug_121](https://cloud.githubusercontent.com/assets/6876373/10856998/d0f19f52-7f21-11e5-85ef-0f50d193228f.png)

**Comment by bcompter** [comment]
And for what it's worth, Cairo is cairo-1.14.2_1

**Comment by andymeneely** [comment]
Ok it's definitely a bug in Pango/Cairo dependency then. You do have the latest Pango - but I wonder if the Ruby bindings have some sort of incompatibility. I'll try to reproduce this on my mac this weekend. I'll be trying out different (older) versions of pango to see where this went wrong.

**Comment by andymeneely** [comment]
Ok I happen to have Pango 1.36 on my Mac (also OSX 10.10) and I get the exact same result. Looks like a bug in Pango. My next step is to try this out in C and see if it's ruby-pango or just pango.

**Comment by andymeneely** [comment]
What do you get when you ask Pango for its version from within ruby?
```
$ irb
2.2.1 :001 > require 'pango'
 => true 
2.2.1 :002 > Pango::Version::STRING
 => "1.38.1" 
```
For me, I used to get a *much* older version. I did a `brew uninstall pango` -- twice -- and got rid of some old pangos. I then re-installed and got 1.38.1 - which seems to be the latest brew has to offer. My bug script worked. 

Let me know if this works. I'm thinking that ruby-pango binds to any old library it finds instead of the latest.

**Comment by bcompter** [comment]
$ irb
2.2.1 :001 > require 'pango'
 => true 
2.2.1 :002 > Pango::Version::STRING
 => "1.38.0" 
2.2.1 :003 > 

I'll try the uninstall trick...

**Comment by bcompter** [comment]
Reinstall of Pango yields the same results for me.  Still 1.38.0 and the bug and text_options output look the same.

**Comment by andymeneely** [comment]
Now that is strange because I was able to reproduce the problem and it went away by getting it to 1.38.1. The behavior could go away between 1.38.0 and 1.38.1 (their [changes](http://ftp.gnome.org/pub/GNOME/sources/pango/1.38/pango-1.38.1.changes) are here). They upgraded their minimum HarfBuzz, which handles the shaping engine, and that's what's failing here.

Not sure why brew didn't give you the latest. Maybe do a `brew update` and then `brew upgrade pango`?

**Comment by bcompter** [comment]
Huzzah!  That worked.  Pango 1.38.1 does the trick.

I needed to brew update twice though.  Seems like it is a fresh bug with brew.
https://github.com/Homebrew/homebrew/issues/45616

**Comment by andymeneely** [comment]
Nice!
