### ISSUE TITLE
Use require_relative instead of require on gem internals

### ISSUE THREAD

**Issue by andymeneely** [andymeneely/squib#130]
From #129 

> As for require vs. require_relative, current best practices are to use require for external libraries and require_relative for internal files. One of the reasons is that you can't load files out of the load path with require for security reasons. Using require_relative allows the code to operate even if not installed as a gem. Is there a technical reason you prefer to use require?

As far as a common convention, the [style guide I try to follow](https://github.com/bbatsov/ruby-style-guide) is silent on this. RubyGems doesn't specify. I remember seeing that [Bundler uses require this way](https://github.com/bundler/bundler/blob/master/lib/bundler.rb), but that could be for legacy reasons. The new ActionCable library in Rails uses the `require_relative` convention, whereas some of their older libraries appear to use `require`. This [Ruby bug](https://bugs.ruby-lang.org/issues/8781) is a fun read on the topic but I don't see a consensus. If there is a respected style guide out there that says something I'd be happy to change - I'm not aware of any.

For me, I originally chose not to use `require_relative` because:
  * Moving files around is more annoying with `require_relative`. But that's debatable.
  * The organization of the gem overall is more visually apparent from those requires. 
  * Building the whole gem as part of my workflow is important to me. I catch more problems by making myself do `rake run[sample]` than if I just run my code directly. Sometimes I leave in debugging code from a prior run that I forgot about or something. I think of it like continuous integration, but at the local level. So yeah - I don't want the code to operate without being installed as a gem. And `rake install` or `rake run[foo]` is fast enough anyway that installing the gem is no hassle at all.

**Comment by andjd** [comment]
I've been working from a fresh clone, and using your workflow.  In my environment, compiling and installing squib as a gem takes 10-15 seconds each time, where as simply loading the file in pry only takes around 1-2 seconds.  

I respect your workflow, but for me, having the require relative structure would make me more efficient when working on this code.

**Comment by andymeneely** [comment]
Huh, weird. It's 1-2 seconds for me. That's fine we can switch over to require_relative. I'll make the change in the dev branch tonight.

**Comment by andymeneely** [comment]
Should be done now - when I bring master up to date this'll get closed.
