### ISSUE TITLE
calc function

### ISSUE THREAD

**Issue by andjd** [andymeneely/squib#132]
I'm considering writing a calc function which would expose the Squib::Args::UnitConversion::parse method.  This would let you do inline math operations on values written as "1.5in" or "2cm". For example:

```
Squib::Deck.new do 
  rect     x: "0.5in", 
           y: "0.5in", 
           height: calc("0.5in") + calc("3cm"), 
           width: calc("2.5in") - 2 * calc("0.5in")
end
```

**Comment by andymeneely** [comment]
Use the inches() method for this. http://andymeneely.github.io/squib/doc/Squib/Deck.html#inches-instance_method
