### ISSUE TITLE
Generate basic scripts for Tabletop simulator

### ISSUE THREAD

**Issue by andymeneely** [andymeneely/squib#139]
Looks like Tabletop Simulator just added a [Lua scripting engine](http://berserk-games.com/knowledgebase/scripting/). It would be cool if we could have some sort of set of hints that generates a base lua script. Squib and Tabletop simulator have very different goals, but I think it would be cool if you could transition you work from one to the other. Even if it's just generating a few templates or something.

If someone else wants to play around with this, I'm all for it. Gists are welcome, pull requests are a long ways off but I'm open to some integration with tools like this.

**Comment by bcompter** [comment]
Yet another reason to splurge for a copy of TTS.  Perhaps all the ComputerCraft mod playtime will come in handy...

This would be cool.

**Comment by andymeneely** [comment]
I know, right? I'm excited to see more of these simulators come out. They're super complicated and I don't want to re-invent any of those wheels, but some simple ways to transition back and forth would be really cool. I'm gonna try to do this on a game I'm prototyping right now (the game that's keeping me from doing feature development on Squib at the moment...)

**Comment by andymeneely** [comment]
I started doing some Tabletop Simulator stuff. So it's looking like `save_sheet` was most of what I needed to do. Here's a video about it: https://www.youtube.com/watch?v=UamjG8u8j7A&t=11s&index=11&list=PLLcm4ZswgXFYk6KKW_ISd8Kf9UGTV9Cfj
