### ISSUE TITLE
Making nokogiri optional dependency?

### ISSUE THREAD

**Issue by andjd** [andymeneely/squib#140]
Am I correct in my understanding that the dependence on the Nokogiri gem is used only for parsing XLSX documents?  In my experience installing squib on multiple systems, nokogiri has always been a particular headache to install, and for me the payoff is negligible since I usually import from CSV anyways.  How would you feel about extracting the functionality into a separate gem or an option disabled by default (eg `$ gem install squib --with_xlsx_parser`)?

**Comment by andymeneely** [comment]
Nokigiri did have a bug recently for Windows that they fixed in the latest version, so they're back to installing easily there. I rarely have issues on other systems anymore. I'd rather not complicate the install process, but we can talk about this if there are more votes for it.

**Comment by andymeneely** [comment]
I'm adding Nokogiri as an explicit dependency for Squib v0.13. Turns out Roo (the library that does the XLSX heavy-lifting) is pretty lax about Nokogiri versions. This allows me to upgrade/downgrade if I hear of Nokogiri issues. Although I haven't heard any complaints about Nokogiri in months.

**Comment by andymeneely** [comment]
Looks like locking in version each release was the right practice to adopt as we haven't had nokogiri issues reported in a long time. So I'm closing this.

**Comment by andymeneely** [comment]
Alright I'm so sick of nokogiri. They STILL don't support Ruby 2.7. 

https://github.com/sparklemotion/nokogiri/issues/1961

I'm reopening this and will prioritize it.
