### ISSUE TITLE
Word wrap

### ISSUE THREAD

**Issue by luyzdeleon** [andymeneely/squib#142]
Hello,

I'm having some trouble wrapping some long text for effect descriptions. I have:

- Added a **height** property in the label.
- Added a **height** parameter in the text method call.
- Changed font to 'Arial 20' to make the text smaller.

Any suggestions of what i might be missing?

**Comment by luyzdeleon** [comment]
There's an issue in the documentation, it mentions on the **wrap** parameter that you only need to specify height, but you need to specify width as well.

**Comment by andymeneely** [comment]
I'll fix that!

**Comment by luyzdeleon** [comment]
Thanks!
