### ISSUE TITLE
Old docs?

### ISSUE THREAD

**Issue by andjd** [andymeneely/squib#144]
Is there a way to access the old version of the Docs?  The new docs still have some holes and I'm having trouble finding some of the method references (e.g. text embeds ...)

**Comment by andymeneely** [comment]
Oops! Sorry I JUST took those down. I still have the original text in the source code: 

https://github.com/andymeneely/squib/blob/master/lib/squib/api/text_embed.rb

I'll also post the text embed docs on the new site ASAP. If you see any other holes let me know.

**Comment by andymeneely** [comment]
Should be up on the new docs now: http://squib.readthedocs.org/en/latest/dsl/text.html

Again, hit me here if you find another thing I missed.

**Comment by andymeneely** [comment]
Since I haven't seen more issues, I'll go ahead and close this one. Feel free to file more bugs if you see docs missing on the new site.
