### ISSUE TITLE
Newline in CSV File not working

### ISSUE THREAD

**Issue by cuken** [andymeneely/squib#145]
Forgive me if I'm missing something SUPER obvious but I can't get this to work for the life of me. If I'm using a CSV or XLSX file as an input for data, when attempting to use the newline escape character, the code is being output to the card. Is it possible to include the "\n" within the middle of a text string and have squib properly new line as expected?

Example: demo.csv
name,"rule","cost","art"
Demo,"Please make a\n new line",Please make a\n line,"somefile.png"

I've tried including quotes around just the \n but that results in an error when building the deck.

**Comment by Qgel** [comment]
I don't think csv works like this. See [RFC 4180](https://tools.ietf.org/html/rfc4180) Section 2.6. If you want a newline, just use a newline in the file, i.e.:

```
name,rule,cost,art
Demo,"A line that has
a newline in it",500,"somefile.png"
```

**Comment by cuken** [comment]
This did not work. if you include the string within `''` it ignores the return char within the csv file. If you don't, it messes up the output in general.

**Comment by Qgel** [comment]
It works fine for me. Try the following:
Create a new squib project with `squib new test`
Paste the example data above into a `test.csv`
Replace the `deck.rb` with the following
```
require 'squib'
data = Squib.csv file: 'test.csv'

Squib::Deck.new(cards: data['rule'].size, layout: 'layout.yml', width: 500, height:200) do
  text str: data['rule']
  save format: :png
end
```
Running this gives me the following result with the expected linebreak.
![card_00](https://cloud.githubusercontent.com/assets/1146690/14001445/283e3054-f146-11e5-9024-81c3727a7b4d.png)

**Comment by andymeneely** [comment]
Yeah the quoting should allow for newlines. And the quotes are usually double-quotes. Can you provide a minimal example of what's failing?

**Comment by andymeneely** [comment]
Just for my own sanity I added a unit test for this. Go ahead and check out the example I added in the linked commit above.

**Comment by andymeneely** [comment]
I've been pondering this lately as it applies to a game I've been working on. CSV is not the best format for editing newline-rich data for this very reason. But it should be relatively easy to do a search and replace on your own data. For one, you  I recently added a feature to the xlsx method that I think should also be in CSV - see #108. 

As another workaround, though, you can always use Ruby to do some preprocessing. Maybe something like this:

```ruby
data = Squib.csv file: 'data.csv'
data['Description'].each { |str| str.gsub! /%n/, "\n" } #replaces %n with newline
```
