### ISSUE TITLE
PDFs created by save_pdf are not flushed until the program exits.

### ISSUE THREAD

**Issue by Qgel** [andymeneely/squib#150]
PDFs seem to not be saved correctly until the script exits. I'm guessing the file is not flushed? I stumbled upon this when I wanted to use the created PDF in the next step of my build process.

Steps to reproduce

1. Create a new project with squib new
2. Change deck.rb to call save_pdf
3. Add `sh 'md5sum _output/output.pdf'` to the :deck target in the Rakefile
4. Run rake 
5. Run the above md5sum command from shell
6. The hashes differ.

A workaround is to change the `load deck.rb` in the rakefile to `sh 'ruby deck.rb'`.

**Comment by andymeneely** [comment]
Fixed! Forgot to flush :flushed: . Fix will be in the next release, coming out soon.
