### ISSUE TITLE
Font fails to load if text only consists of embedded images

### ISSUE THREAD

**Issue by programmingisgood** [andymeneely/squib#153]
Here is a simple example:

```ruby
text(str: "(G)", x: 50, y: 1600, width: 1400, height: 450, markup: true,
     font: 'Verdana, 46', color: "#FFFFFF", align: :center, valign: :middle) do |embed|
    embed.png key: '(G)', width: 50 * mod, height: 50 * mod, dx: 0, dy: -8, file: 'art/guard_icon.png'
end
```

If I use 'Verdana, 46' above this line and do include normal text, it will work properly so there is some kind of ordering issue here.

Here is the error I am seeing:
```
D:/Ruby22/lib/ruby/gems/2.2.0/gems/squib-0.9.0/lib/squib/graphics/text.rb: line 97
   Pango-WARNING **:failed to choose a font, expect ugly output. engine-type='PangoRenderWin32', script='latin'
D:/Ruby22/lib/ruby/gems/2.2.0/gems/squib-0.9.0/lib/squib/graphics/text.rb: line 97
   Pango-WARNING **:failed to choose a font, expect ugly output. engine-type='PangoRenderWin32', script='common'
```

**Comment by andymeneely** [comment]
(edited description above to have syntax highlighting)

**Comment by andymeneely** [comment]
Does it still work? Technically those are just warnings.

As a workaround, does padding a space to the end of the string still cause problems? That is, `str: "(G) "`. 

As an aside, I'm pretty unhappy with how we accomplish our embedded icons feature. It's hacky and utilizes zero-sized fonts which is probably undefined or just inconsistent behavior. I've sent an email to the Pango mailing list asking for help. Maybe we can do this whole embedded icon feature the way Pango meant it to be accomplished. Thanks for being patient on this one.

**Comment by andymeneely** [comment]
Ew, even more annoyingly on my Windows machine I get some nasty characters and not even a Pango warning. Here's a smaller test case using the game_icons gem:

```ruby
require 'squib'
require 'game_icons'

Squib::Deck.new do
  background color: '#ccc'
  text(str: "(G)", font: 'Verdana, 46') do |embed|
      embed.svg key: '(G)', width: 50, height: 50,
                file: GameIcons.get('glass-heart').file
  end
  save_png dir: '.'
end
```

**Comment by andymeneely** [comment]
Ha! I've got a "better" solution that doesn't utilize zero-sized fonts. Instead of using zero-sized "a" in our replacement, we can just use a control character. Turns out `\u0091` is intended for private use, so it won't clash with anything else. Pango just doesn't render it, but still respects its letter-spacing attribute - carving out the space we need.

I need to do more testing but I'll probably get this fix into the next release. My above example works fine and none of my prior tests fail either.

I'm still curious what the Pango people say though.

**Comment by andymeneely** [comment]
AND, it fixes my other nemesis, #103. :+1:

**Comment by programmingisgood** [comment]
I got the same nasty characters you referenced along with the error (Windows).

The embedding feature is really useful (even with these minor issues) :)

**Comment by andymeneely** [comment]
Actually the fix will need to be in the library itself. I'll push my fix tonight and you can try it then.

**Comment by andymeneely** [comment]
Gah! Sorry I said I would post the fix and then forgot about it for 11 days. I pushed it now. It's in both the dev and master branch, so if you want to do the [beta tester thing](http://squib.readthedocs.org/en/latest/help.html#beta-using-pre-builds) and try it out from those branches. It fixes my test cases - let me know if it fixes yours.

**Comment by programmingisgood** [comment]
I can confirm 0.10 has fixed my issue. Thanks again :+1:

**Comment by andymeneely** [comment]
Awesome. I hereby pronounce this bug dead. :boom:
