### ISSUE TITLE
svg not rendering (no error)

### ISSUE THREAD

**Issue by stverhae** [andymeneely/squib#155]
I'm having trouble getting a specific svg to render in squib. Its a public vector image I found here:
https://upload.wikimedia.org/wikipedia/commons/8/80/Magic_font_awesome.svg
I have no problem with other svg's but this one simply wont render, no error or nothing.
It displays fine in inkscape. I'm new to the whole svg thing so maybe I'm missing something here.

PS: quickly want to express my gratitude for making this project. It's scazy, sometimes you find exactly what you're looking for ... and in my favorite programming language too!!  Pure awesomeness!

**Comment by andymeneely** [comment]
Woah - you're right! Here's my reproducing case:

```ruby
require 'squib'

Squib::Deck.new do
  svg file: 'Magic_font_awesome.svg', width: 100, height: 100
  save_png
end
```

**Comment by andymeneely** [comment]
Ah! I got it. So this was the culprit: 

```xml
style="fill:currentColor" 
```

The "default" color internally is the empty color - whereas the default may be different elsewhere. Just remove it and it should work.

**Comment by stverhae** [comment]
Wow, that was a very fast reaction, Thaks a lot!!!
I didn't know you could open svg files in a text editor, awesome.
Tested and your solution works perfectly, thanks again!!!

**Comment by andymeneely** [comment]
No problem. Yeah SVGs are just XML. They're pretty readable in general - although Inkscape clutters things up a lot sometimes. 

If you *really* want to your mind blown, you can use Nokogiri to modify your SVGs directly in your Squib code. This lets you customize the SVG itself - like what I [did here](https://github.com/andymeneely/game_icons/blob/master/lib/game_icons/icon.rb)

And thank you for the nice words!
