### ISSUE TITLE
Embed Text Sample Produces Odd Results on OSX

### ISSUE THREAD

**Issue by bcompter** [andymeneely/squib#158]
Running the embed text sample produces additional characters.
![embed_00](https://cloud.githubusercontent.com/assets/6876373/15236418/542747a0-1892-11e6-8ee2-b4198f3fa091.png)

**Comment by andymeneely** [comment]
:rage: I'll take a look when I can.

**Comment by Nibodhika** [comment]
I can confirm this on Linux too. I've got around it by changing 

```ruby
 str = str.sub(key, "\u0091<span letter_spacing=\"#{spacing.to_i}\">\u0091</span>\u0091")
```

to:

```ruby
str = str.sub(key, " <span letter_spacing=\"#{spacing.to_i}\"> </span>")
```

(i.e. removing the \u0091 and replacing it with whitespaces) in squib/lib/squib/graphics/text.rb

I don't know the implications of this, but on my tests it seems to be working.

**Comment by andymeneely** [comment]
Replacing those characters with a space means that you won't have multiple icons in a row abut (see #30). For this method we need a zero-width character - but different OS's interpret those characters differently. I have different solutions that work for different OS's, but there's also a cleaner way to carve out the space that I'm working on.
