### ISSUE TITLE
Add Suffix Option for Saving Files

### ISSUE THREAD

**Issue by bcompter** [andymeneely/squib#159]
I already know and love the prefix option for saving files.  What I would love to have is a Suffix option as well.

The GameCrafter image uploader has a unique parser that can automatically update your existing art images based on the prefix and suffix.

For instance, token_00[face].png will update the face of asset token00 with the uploaded image.  token_00[all].png will update both sides.  token_00[back].png will update only the back.

The ability to add a suffix to my final images would be very useful for those who work with TheGameCrafter.

**Comment by andymeneely** [comment]
I definitely can do this, but in the meantime you can use the `count_format` for this:

```
save_png count_format: '%02d[face]`
save_png count_format: '%02d[back]`
```

**Comment by bcompter** [comment]
I learn more about this tool every day.  Thanks!
