### ISSUE TITLE
Unit Conversion should support millimeters

### ISSUE THREAD

**Issue by lcarlsen** [andymeneely/squib#161]
The unit conversion code should support millimeters (mm) as a unit.

I was surprised that '55mm' as a width specification for cards triggered an error.  Millimeters seem like a more-natural fit for card sizes than cm.  Fantasy flight, for example, provides sizes for their sleeves in inches and mm.  Many common sizes do not fall into whole number units of centimeters, but do for mm.  For example 44x68mm (mini euro), 41x63mm (mini american), 57x89mm (standard american), 59x92mm (standard euro), etc.

```
// Something like this should work
Squib::Deck.new(width: '30mm') do
  //...
end
```

**Comment by andymeneely** [comment]
Makes sense. I'll add that into the next release.

**Comment by andymeneely** [comment]
It's in the dev and master branch now in case you want to test it out (http://squib.readthedocs.io/en/latest/help.html#help-by-beta-testing)

**Comment by lcarlsen** [comment]
There's one more spot to add mm so I can also use mm in custom layouts.

```
diff --git a/lib/squib/args/arg_loader.rb b/lib/squib/args/arg_loader.rb
index 56e066a..a99a8d6 100644
--- a/lib/squib/args/arg_loader.rb
+++ b/lib/squib/args/arg_loader.rb
@@ -126,6 +126,8 @@ module Squib
           arg.rstrip[0..-2].to_f * dpi
         when /cm$/ # ends with "cm"
           arg.rstrip[0..-2].to_f * dpi * INCHES_IN_CM
+        when /mm$/ # ends with "mm"
+          arg.rstrip[0..-2].to_f * dpi * INCHES_IN_CM / 10.0
         else
           arg
         end
```

**Comment by andymeneely** [comment]
Ah - that code should be ripped out anyway to avoid duplicate functionality. I'll incorporate that as soon as I can.
