### ISSUE TITLE
Google Sheets support

### ISSUE THREAD

**Issue by jamie** [andymeneely/squib#164]
Just looking for some quick and dirty google sheets support.

If you have a doc that has **Link Sharing on**, you can get a CSV download link from a fairly trivial URL transform:

```
# Browser URL
https://docs.google.com/spreadsheets/d/{doc_id}/edit#gid={sheet_id}
# CSV URL
https://docs.google.com/spreadsheets/d/{doc_id}/export?format=csv&id={doc_id}&gid={sheet_id}
```

I'm using the following hack right now to load this data, but it'd be nice if I could just say `data = Squib.google_sheet(url: "...")`

```
require 'open-uri'
sheet_uri = "https://docs.google.com/spreadsheets/d/.../edit#gid=..."
csv_uri = sheet_uri.gsub(%r{/d/(.*)/edit#}, '/d/\1/export?format=csv&id=\1&')
csv = open(csv_uri).read

data = Squib.csv(data: csv)
```

**Comment by andymeneely** [comment]
See #49. I'm not planning on supporting Google Sheets anytime soon. 

Google made my (work) life a pain when they kept changing their APIs and behaviors without warning. I used to use Ruby to connect to Google Spreadsheets, but they made it *way* more difficult to do it right without the security hole of turning on link sharing. Technically, the feature you're using is undocumented and unsupported by Google, which means Squib could break at any time if I ship with it. Instead, we can just keep code snippets like this around with the understanding that Google does what Google does.

If you don't like having code like that in your main Squib source code, you can always just declare a Ruby method and put it in another file. I like to have a `squib_helpers.rb` in my code, like this: 

https://github.com/andymeneely/project-timber-wolf/blob/master/src/characters.rb#L2
and
https://github.com/andymeneely/project-timber-wolf/blob/master/src/helpers.rb

**Comment by jamie** [comment]
That's fair. Thanks for the response.
