### ISSUE TITLE
Generated projects should include guard-rake

### ISSUE THREAD

**Issue by spilth** [andymeneely/squib#165]
I've been using [guard-rake](https://github.com/rubyist/guard-rake) to watch my project files and re-run the `deck` Rake task when there's a change in any of them, resulting in a fast feedback cycle for working on my card game. It would be cool if squib supported this out of the box.

Here's my Guardfile: https://github.com/spilth/madworld/blob/master/Guardfile

I'd be happy to submit a pull request if you're interested in this functionality.

**Comment by andymeneely** [comment]
Yeah I love Guard. I use it too. Here's one of mine: https://github.com/andymeneely/project-timber-wolf/blob/master/Guardfile

Go ahead and write a Guardfile. Be sure to comment it thoroughly and tell people it's optional. Put in a whatever `gem` calls we need in the Gemfile too (commented out).

**Comment by spilth** [comment]
@andymeneely Cool. I'll work on this when I have some time.

**Comment by andymeneely** [comment]
Been working with Guard in my prototyping process for months now and I really like it. Combined with build groups it's a better thing too. Making this a priority for myself or whoever wants to pick it up.

**Comment by sparr** [comment]
I'm new around here. Can someone clue me in on "generated projects"? Is there a toolchain that's producing barebones squib projects?

**Comment by andymeneely** [comment]
On the command line if you do `squib new foo` it'll create a directory called `foo` with lots of files set up for you. 

To add to the default template, the file goes into https://github.com/andymeneely/squib/tree/master/lib/squib/project_template

Basically coming up with a Guardfile that has some good defaults for Squib and a bunch of comments explaining it would be great.

**Comment by andymeneely** [comment]
We have this now! It's in the `--advanced` option on `squib new`
