### ISSUE TITLE
Block-based Range Generation

### ISSUE THREAD

**Issue by spilth** [andymeneely/squib#167]
I'm generating a deck of cards where I want an image to be drawn with a border if an image name is provided in my CSV. If no image name is provided then I don't want to draw an image or the border.

I wanted a succinct way to do this and came up with the following. I'm curious if you have a simple or better way. If not, would you be interested in adding the filter_indexes method in with squib somehow?

## cards.csv

    name,type,image,description,quote
    Landmaster,Vehicle,landmaster.png
    "The Interceptor","Vehicle",interceptor.png,Blah blah blah,"The last of the V8 Interceptors... a piece of history!"
    180,"Manuver",,You do a 180,Yeeeee-hawwww!

## deckrb

    require 'squib'
    
    card = Squib.csv file: 'cards.csv'
    
    class Array
      def filter_indexes
        each_with_index.inject([]) do |indexes, (value, index)|
          indexes << index if yield value
          indexes
        end
      end
    end
    
    Squib::Deck.new(cards: card['name'].size, layout: 'layout.yml') do
      png file: card['image'], layout: 'image', range: card['image'].filter_indexes { |image| !image.nil? }
      rect layout: 'image-border', range: card['image'].filter_indexes { |image| !image.nil? }
      
      save_png prefix: card['type']
    end

This way I end up with the following:

![vehicle01](https://cloud.githubusercontent.com/assets/13157/17087443/05e98272-51d8-11e6-97f0-4c4f06d51fd3.png)

![manuver02](https://cloud.githubusercontent.com/assets/13157/17087444/09c19646-51d8-11e6-83f9-fdcd58ae0f25.png)

**Comment by spilth** [comment]
A little more iterating on this:

```ruby
classs Array
  def select_indexes
    each_with_index.inject([]) do |indexes, (value, index)|
      indexes << index if yield value
      indexes
    end
  end

  def reject_indexes
    each_with_index.inject([]) do |indexes, (value, index)|
      indexes << index unless yield value
      indexes
    end
  end
end

# ...

  png file: card['image'], layout: 'image', range: card['image'].reject_indexes(&:nil?)
  rect layout: 'image-border', range: card['image'].reject_indexes(&:nil?)
```

**Comment by spilth** [comment]
FWIW, I eventually found https://github.com/andymeneely/squib/issues/124 😄

**Comment by andymeneely** [comment]
So you got it working? Sorry I missed this initially.

**Comment by spilth** [comment]
@andymeneely Yup! And I eventually turned it into a refinement.

## spilth_additions.rb

```
module SpilthAdditions
  refine Array do
    def select_indexes
      each_with_index.inject([]) do |indexes, (value, index)|
        indexes << index if yield value
        indexes
      end
    end

    def reject_indexes
      each_with_index.inject([]) do |indexes, (value, index)|
        indexes << index unless yield value
        indexes
      end
    end
  end
end
```

## deck.rb

```
require 'squib'
require_relative 'spilth_additions'

using SpilthAdditions
...
```

**Comment by andymeneely** [comment]
Great! Yeah I'll probably include some version of these in the next release.
