### ISSUE TITLE
Post previews of built-in layouts 

### ISSUE THREAD

**Issue by briant-spindance** [andymeneely/squib#169]
Squib's built-in layouts are great. It would be nice to have a "preview" (png, jpg, whatever) in the docs to allow users to see the options quickly.

Here's where I'm thinking the previews could go:
http://squib.readthedocs.io/en/latest/layouts.html#squib-comes-with-built-in-layouts

**Comment by andymeneely** [comment]
Good idea. I already have some scripts in my samples directory that put those together: 

https://github.com/andymeneely/squib/blob/master/samples/layouts_builtin.rb

But I can work toward getting it on the website too.

**Comment by andymeneely** [comment]
Doing this in commit c8e1daf79ddf04f022c10932bc3d53d426e5996a

**Comment by andymeneely** [comment]
Here you go! Now we just need more!!

http://squib.readthedocs.io/en/latest/layouts.html#squib-comes-with-built-in-layouts
