### ISSUE TITLE
Embedding Images is not working

### ISSUE THREAD

**Issue by Nibodhika** [andymeneely/squib#171]
I tried several things, until I wrote the minimum script based on the docs and I'm getting an error

```ruby
Squib::Deck.new cards: 1, layout: 'layout.yml' do
  text(str: 'Gain 1 :health:') do |embed|
    embed.svg key: ':health:', file: 'health.svg'
  end
  save_png
end
```

I get the following error:

```
/home/nibodhika/.gem/ruby/2.3.0/gems/squib-0.10.0/lib/squib/graphics/text.rb:86:in `process_embeds': undefined method `*' for :native:Symbol (NoMethodError)
        from /home/nibodhika/.gem/ruby/2.3.0/gems/squib-0.10.0/lib/squib/graphics/text.rb:149:in `block in text'
        from /home/nibodhika/.gem/ruby/2.3.0/gems/squib-0.10.0/lib/squib/card.rb:50:in `use_cairo'
        from /home/nibodhika/.gem/ruby/2.3.0/gems/squib-0.10.0/lib/squib/graphics/text.rb:124:in `text'
        from /home/nibodhika/.gem/ruby/2.3.0/gems/squib-0.10.0/lib/squib/api/text.rb:20:in `block in text'
        from /home/nibodhika/.gem/ruby/2.3.0/gems/squib-0.10.0/lib/squib/args/card_range.rb:13:in `block in each'
        from /home/nibodhika/.gem/ruby/2.3.0/gems/squib-0.10.0/lib/squib/args/card_range.rb:13:in `each'
        from /home/nibodhika/.gem/ruby/2.3.0/gems/squib-0.10.0/lib/squib/args/card_range.rb:13:in `each'
        from /home/nibodhika/.gem/ruby/2.3.0/gems/squib-0.10.0/lib/squib/api/text.rb:20:in `text'
        from ./deck.rb:4:in `block in <main>'
        from /home/nibodhika/.gem/ruby/2.3.0/gems/squib-0.10.0/lib/squib/deck.rb:74:in `instance_eval'
        from /home/nibodhika/.gem/ruby/2.3.0/gems/squib-0.10.0/lib/squib/deck.rb:74:in `initialize'
        from ./deck.rb:3:in `new'
        from ./deck.rb:3:in `<main>'
```

Probably some dependency not being installed? I'm new to ruby, so I have no idea what it could be, and google doesn't seem to be helping. I did see this same issue being discussed in BGG (https://boardgamegeek.com/thread/1293453/introducing-squib-ruby-gem-prototyping-games-lates/page/4) over a year ago.

**Comment by Nibodhika** [comment]
Did some tests, apparently it's caused by width and height of the embebed.svg being set to native so this line

```ruby
 spacing = rule[:box].width[@index] * Pango::SCALE
```

doesn't know how to multiply a string and a number.

If I write with explicit parameters like:

```ruby
 embed.svg key: ':health:', file: 'health.svg', width: 30, height: 30
```

Then it works. But it's placing a 0091 character before and two after the icon, but this is probably only annoying to me because my pdf-viewer is insisting on showing me there are characters there.

If this is an expected behavior, it should be in the docs that width and height are required, because the docs clearly gives an example without it.

**Comment by andymeneely** [comment]
I'm working on a better implementation of all of this for the next release, so this should go away soon. Yeah the docs are wrong for now... but it should support `:native` anyhow.

**Comment by andymeneely** [comment]
So the native thing is not going to happen for this release. I'm still going with the zero-width character workaround. I think I can get the cleaner solution done for this, but I have some corner cases to still work out.  

If you're up for it, I could use some beta testing. I'm putting v0.11 into beta for a day or two until I get the green light from folks. 

If you want to join the mailing list for that, go ahead and join https://groups.google.com/forum/#!forum/squib-testers

And you can read about how to beta test here:
http://squib.readthedocs.io/en/latest/help.html#help-by-beta-testing
