### ISSUE TITLE
layout_parser does not properly support unit conversion when using add/subtract relative operators.

### ISSUE THREAD

**Issue by rhyok** [andymeneely/squib#173]
Hello!

The documentation seems to suggest that I should be able to do something like the following:

layout.yml:
```
test:
  x: 1in

testExtended:
  extends: test
  x: +=0.1in
```

But when running this through the layout_parser, I get the following error:
```
F:/Programs/Ruby22-x64/lib/ruby/gems/2.2.0/gems/squib-0.10.0/lib/squib/layout_parser.rb:46:in `+': no implicit conversion of Float into String (TypeError)
        from F:/Programs/Ruby22-x64/lib/ruby/gems/2.2.0/gems/squib-0.10.0/lib/squib/layout_parser.rb:46:in `block (2 levels) in recurse_extends'
        from F:/Programs/Ruby22-x64/lib/ruby/gems/2.2.0/gems/squib-0.10.0/lib/squib/layout_parser.rb:44:in `merge'
        from F:/Programs/Ruby22-x64/lib/ruby/gems/2.2.0/gems/squib-0.10.0/lib/squib/layout_parser.rb:44:in `block in recurse_extends'
        from F:/Programs/Ruby22-x64/lib/ruby/gems/2.2.0/gems/squib-0.10.0/lib/squib/layout_parser.rb:43:in `each'
        from F:/Programs/Ruby22-x64/lib/ruby/gems/2.2.0/gems/squib-0.10.0/lib/squib/layout_parser.rb:43:in `recurse_extends'
        from F:/Programs/Ruby22-x64/lib/ruby/gems/2.2.0/gems/squib-0.10.0/lib/squib/layout_parser.rb:19:in `block (2 levels) in load_layout'
        from F:/Programs/Ruby22-x64/lib/ruby/gems/2.2.0/gems/squib-0.10.0/lib/squib/layout_parser.rb:18:in `each'
        from F:/Programs/Ruby22-x64/lib/ruby/gems/2.2.0/gems/squib-0.10.0/lib/squib/layout_parser.rb:18:in `block in load_layout'
        from F:/Programs/Ruby22-x64/lib/ruby/gems/2.2.0/gems/squib-0.10.0/lib/squib/layout_parser.rb:13:in `each'
        from F:/Programs/Ruby22-x64/lib/ruby/gems/2.2.0/gems/squib-0.10.0/lib/squib/layout_parser.rb:13:in `load_layout'
        from F:/Programs/Ruby22-x64/lib/ruby/gems/2.2.0/gems/squib-0.10.0/lib/squib/deck.rb:71:in `initialize'
        from deck.rb:3:in `new'
        from deck.rb:3:in `<main>'
```

Looking at your parser, I can see what the issue is: you expect that the right hand value passed to this operator can be converted to float. This is not the case if the RHV is something like "0.5in"

You need to handle addition of units by hand in the parser. A quick and dirty solution is something along the lines of (and this is pseudoRuby-ish code, not real Ruby. I'm still a newbie!):
```
if child_val.to_s.strip.start_with?('+=')
  bare_child_val = chil_val.sub('+=', '')
  supportedUnits = ['in', 'pt', 'px'] #fill in your supported units here
  child_is_unit = bare_child_val.end_with?('in', 'pt', 'px') #number had a units specifier
  unitFoundChild = ''
  supportedUnits.each do |unit|
    if bare_child_val.end_with?(unit)
      unitFoundChild = unit
  end
  #
  # TODO: logic to check if child unit == parent unit. If not, throw error
  #

  #
  # TODO: Throw error if unitFoundChild == '', could not find supported unit.
  #
  if child_is_unit
    child_num_val = child_val.sub('+=', '').sub(unitFoundChild, '').to_f #missing other unit kinds
    parent_num_val = parent_val.sub('+=', '').sub(unitFoundChild, '').to_f #missing other unit kinds
    (parent_num_val + child_num_val).to_s + unitFoundChild
  else
    parent_val + child_val.sub('+=', '').strip.to_f
```

This would replace lines 45-46 in lib/squib/layout_parser.rb

I would recommend NOT supporting things like:
```
test:
  x: 1in

testExtended:
  extends: test
  x: +=50px
```
because you'd have to do the unit conversion at YAML parsing time.

I'd try my hand at fixing this and submitting a pull request, but I'm not yet versed in Ruby and don't know how to compile your library to even test this, so sorry homie! :( I hope this helps you figure out how you'd do this.

**Comment by rhyok** [comment]
And by the way man, everything else I've seen from this tool so far is awesome! I've been looking for something like Squib for ages (was even starting to code it at one point), and I'm glad you took such an excellent pass at it.

If there's any way I can throw beer money at you, let me know. I'm also prototyping a game with it right now, and if it takes off, I'd feel weird not giving you something for helping bootstrap it.

**Comment by andymeneely** [comment]
Thank you so much for the nice words! Next time you're in Rochester, NY you can get me a beer and we can play your game :)

If you're up for it, I could use some beta testing. I'm putting v0.11 into beta for a day or two until I get the green light from folks. I did put in this feature.

If you want to join the mailing list for that, go ahead and join https://groups.google.com/forum/#!forum/squib-testers

And you can read about how to beta test here:
http://squib.readthedocs.io/en/latest/help.html#help-by-beta-testing
