### ISSUE TITLE
Seeing some weird graphics when using "embed" from the samples

### ISSUE THREAD

**Issue by rpond-pa** [andymeneely/squib#176]
When generating cards from [samples/embed_text.rb](https://github.com/andymeneely/squib/blob/master/samples/embed_text.rb), I'm seeing some weird characters show up in the text.

Anyone seen this?  

### File:  _output/embed_00.png
![embed_00](https://cloud.githubusercontent.com/assets/4094154/18336573/e86097ba-754d-11e6-9de0-5856b6376693.png)

### File:  _output/embed_multisheet_00.png
![embed_multisheet_00](https://cloud.githubusercontent.com/assets/4094154/18336575/eb658d3a-754d-11e6-8553-5e075f821a65.png)

### My details

Branch:  master
Cmd:  `cd samples && ruby embed_text.rb && open _output/`
Ruby:  `ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin13]`
OS:  OSX 10.11.5 (El Capitan)

### Homebrew:

```
$ brew info pango | head -n 1
pango: stable 1.38.1 (bottled), HEAD
$ brew info cairo | head -n 1
cairo: stable 1.14.6 (bottled), devel 1.15.2
$ brew info poppler | head -n 1
poppler: stable 0.44.0 (bottled)
```

## Bundle

```shell
$ bundle
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 11.2.2
Using addressable 2.4.0
Using bundler 1.11.2
Using pkg-config 1.1.7
Using json 2.0.2
Using docile 1.1.5
Using simplecov-html 0.10.0
Using tins 1.12.0
Using thor 0.19.1
Using diff-lcs 1.2.5
Using game_icons 0.33.0.20160822
Using github-markup 1.4.0
Using mercenary 0.3.6
Using mini_portile2 2.1.0
Using redcarpet 3.3.4
Using rubyzip 1.2.0
Using rspec-support 3.5.0
Using ruby-progressbar 1.8.1
Using launchy 2.4.3
Using cairo 1.15.2
Using glib2 3.0.9
Using simplecov 0.12.0
Using term-ansicolor 1.3.2
Using nokogiri 1.6.8
Using rspec-core 3.5.3
Using rspec-expectations 3.5.0
Using rspec-mocks 3.5.0
Using gdk_pixbuf2 3.0.9
Using pango 3.0.9
Using coveralls 0.8.15
Using roo 2.4.0
Using rspec 3.5.0
Using rsvg2 3.0.9
Using squib 0.11.0a from source at `.`
```

**Comment by rpond-pa** [comment]
I've also duplicated this on my own project files outside of the "sample" by using the following snippet.  

```ruby
embed_text = "This is backup :backup"
text(str: embed_text, font: 'Sans 18', x: 0, y: 0, width: 180, align: 'left', ellipsize: false) do |embed|
  embed.svg key: ':backup', width: 28, height: 28, file: 'svg/backup.svg'
end
```

**Comment by andymeneely** [comment]
See discussion around #171, #158. I've got a "final" fix in the works for this, but I'll be putting out a workaround in the next release.

If you would like to test my fix for this, let me know. I could use some testers on this.

**Comment by rpond-pa** [comment]
Sounds good.  Sorry for the issue spam.  Didn't realize it was covered somewhere else.  :)

**Comment by andymeneely** [comment]
No problem - thanks for reporting and getting involved! 

If you're up for it, I could use some beta testing. I'm putting v0.11 into beta for a day or two until I get the green light from folks. 

If you want to join the mailing list for that, go ahead and join https://groups.google.com/forum/#!forum/squib-testers

And you can read about how to beta test here:
http://squib.readthedocs.io/en/latest/help.html#help-by-beta-testing
