### ISSUE TITLE
save_pdf's crop_mark should go the full height/width of the page

### ISSUE THREAD

**Issue by mattparkes** [andymeneely/squib#184]
I love the addition of the crop_mark parameter to save_pdf, however it doesn't seem very practical in it's current state. 

I'm not sure if anyone has used it, but just looking at the generated PDF, without full height/width marks, your very first cut (no matter where you make it) will instantly remove the matching crop mark on the other side of the sheet for every single crop mark running perpendicular to your cut.

Having full height crop marks can leave residual traces of the crop mark colour on cards which are cut slightly wrong, so this is possibly not a sane default, but it would be nice if crop_marks accepted a few different crop mark modes (none, current method, "full", etc).

**Comment by andymeneely** [comment]
You can always do what I did before crop marks and just do a "rect" around your cut line on the card itself.

I think we can also do crop marks that are inside the gap between the cards.

**Comment by andymeneely** [comment]
Or you can use the `line` method, or an svg file, to draw crop lines in the bleed area.

**Comment by andymeneely** [comment]
I've implemented this in my dev branch, but it's not well-tested. Go ahead and test it out.
