### ISSUE TITLE
Generate basic scripts for Tabletopia

### ISSUE THREAD

**Issue by andymeneely** [andymeneely/squib#188]
Tabletopia just got out of Early Access on Steam, so it would be great if someone figured out a workflow to go from Squib to Tabletopia. 

Kinda like #139.

**Comment by mattparkes** [comment]
I'm going to pick this up. 

My ruby is pretty rudimentary and Tabletopia don't currently have an API, but I'll document the POSTs to achieve this and see what I can do from there.

**Comment by andymeneely** [comment]
Awesome! You rock. Yeah documenting what needs to be done on the Tabletopia side would be ideal. I can help out with how it would work in Ruby and/or Squib.

**Comment by andymeneely** [comment]
@mattparkes did you end up getting anywhere on this?
