### ISSUE TITLE
Image pixelation of graphics when using 'mask' in 'svg'

### ISSUE THREAD

**Issue by zelig2** [andymeneely/squib#192]
When I want to apply one color to an entire SVG file I use the 'mask' option. When I do that for anything large the resulting image is pixelated. A work around is creating multiple versions of the SVG files in different colors but that's inefficient. This could possibly be done by scanning the SVG file for all instances of 'fill'.

**Comment by andymeneely** [comment]
Yeah the mask option rasterizes things - it's the only way I could see to implement that feature. For me, I don't use the mask option, I actually just modify the SVG on the fly anyway - that might get what you want.

**Comment by andymeneely** [comment]
Nowadays I don't really favor mask anyway - I more recommend modifying the SVG directly with Nokogiri. You get better results and way more flexibility.

**Comment by andymeneely** [comment]
Yeah we can do that.
