### ISSUE TITLE
Please add One Last Job to projects using Squib on the website

### ISSUE THREAD

**Issue by programmingisgood** [andymeneely/squib#194]
http://www.onelastjobgame.com A 2 player, asymmetric heist card game.

http://squib.readthedocs.io/en/v0.12/guides/projects.html

Thanks :)

**Comment by andymeneely** [comment]
Is there code to share? Or is this just a promotion for your game ;)

**Comment by programmingisgood** [comment]
I must have misinterpreted the intent of that page. I thought you were looking to list project that use Squib. I wasn't intended to promote my game necessarily. I can share code but I'm not sure it would be that interesting.

**Comment by ekstroem** [comment]
I think any examples of how squib is used would be useful

**Comment by programmingisgood** [comment]
My project is pretty big and complicated at this point but I plan to do a video explaining the basics and will provide an example project that is a bit more simplified.

**Comment by andymeneely** [comment]
Yeah it's still good to get your project up there - sorry I didn't mean to imply your request was faux pas. It's a common practice. I've put it up as of f7e5c67a111cd0eeca2bc342677ec34b62d8bc14. (And FTR I don't mind promoting peoples' games with this page - it promotes Squib too!)

One way to share your work with others is to make a one-time Gist of your script and I can link to it. That way you don't have to share all of your assets too and it can just serve as yet another an example. I know I tend to find answers to things in random Gists.
