### ISSUE TITLE
How to change card dimensions

### ISSUE THREAD

**Issue by JKochosky** [andymeneely/squib#197]
I'm just getting started with Squib, and I already think it's fantastic; however, there is one thing that I would love to see. There currently isn't an easy way to alter the size of the card (the **initialize** statement in the Deck class hard-sets it to poker-deck size (825x1125 pixels). I tried creating a second class file by duplicating deck.rb and changing the **width** and **height** dimensions, but I couldn't get the new class to load properly. Is there some way that a parameter could be added to the Deck class to control the card dimensions?

**Comment by bcompter** [comment]
You can have any card dimension you want with Squib right out of the gates.  Just use the height and width properties when you make your deck. Like this...

```ruby
Squib::Deck.new(width: 450, height: 300, cards: 42) do
```

**Comment by JKochosky** [comment]
Many thanks.
