### ISSUE TITLE
Loop iteration based on spreadsheet values

### ISSUE THREAD

**Issue by JKochosky** [andymeneely/squib#198]
I have a project that I'm working on converting into squib, and I'm running across an issue with one of the card elements. Each card has a "Tolerance" value, and I want the card to display a number of icons based on the value; a tolerance of 1 would show the first icon, a tolerance of 3 would show icons 1, 2, and 3, etc.

I've tried multiple methods for achieving this, but haven't hit upon the right one yet.
Method 1 - direct reference to value: ```ArgumentError: bad value for range```
```
(1..data['Tolerance']).each do |key|
    svg file: "Icon#{key}.svg", layout: 'Icon#{key}'
end
```

Method 2 - pull value into variable first: Same error
```
value = data['Tolerance']
(1..value).each do |key|
    svg file: "Icon#{key}.svg", layout: 'Icon#{key}'
end
```

The errors reference the (1..n) line, and never reaches the ```svg``` call (I based that call on Issue #90)

**Comment by bcompter** [comment]
I can think of maybe two ways to do this.  But the easiest may be with ranges as shown in the ranges example.  Let me know if this helps!

```ruby 
# Useful idiom: draw a different number of images for different cards
  hearts = [nil, 1, 2] #i.e. card 0 has no hearts, card 2 has 2 hearts drawn
  1.upto(2).each do |n|
    range = hearts.each_index.select { |i| hearts[i] == n}
    n.times do |i|
      svg file: 'glass-heart.svg', range: range,
          x: 150, y: 55 + i*42, width: 40, height: 40
    end
  end
```

https://gist.github.com/andymeneely/25b0da2a84ab906bd44b

**Comment by JKochosky** [comment]
That might work, but I'm running into a problem with pulling up the image. Here's what I have:
```
  tolerance = data['Tolerance']
    1.upto(4).each do |n|
      range = tolerance.each_index.select { |i| tolerance[i] == n}
      n.times do |i|
        svg file: "icons/Icon#{i}.svg", range: range,
            x: 101 + i*171, y: (i.odd? ? 700 : 750), width: 110, height: 110
      end
    end
```
I'm getting a message that `Icon0.svg` does not exist, but the Tolerance values range from 1 to 4.

**Comment by andymeneely** [comment]
Method 1 should work - I have done that before. But this part looks strange to me:
```ruby
(1..data['Tolerance'])
```
`data['Tolerance']` is an array - and so it doesn't make sense to give it to a range. You could change it `(1..data['Tolerance'].max)` to get the maximum Tolerance value and it'll probably work.

Method 1a: Or, you could `map`:
```ruby
svg layout: data['Tolerance'].map { |t| "Icon#{key}" # define "file" in your Icon1 Icon2 Icon3 layouts
```

Method 2. Is really just Method 1 with extracting data['Tolerance'] to it's own variable - so you'll get the same problem.

**Comment by andymeneely** [comment]
Woo! Concurrent editing. I didn't see your follow-up until I posted mine....

The math there might not be necessary. Put all your coordinates for different icons in the layout file. You can still do some basic math with `+=` and `extends` inside of a layout file.

**Comment by andymeneely** [comment]
Oh and you got a 0 on that because of the `times` - that's basically like `upto`.

**Comment by JKochosky** [comment]
Andy,

The `.map` method isn't quite what I was hoping to do, unless I make seperate images for each of the total number of icons present. I can do that, but it seems kludgy.

What I was looking for was if the card has Tolerance=1, it would show Icon1, if Tolerance=2, it shows Icon1 and Icon2, and so forth.

**Comment by andymeneely** [comment]
Ah! And now that I look at my sample code [here](https://github.com/andymeneely/squib/blob/master/samples/ranges/_ranges.rb#L52-L60) I see you're adapting that. Ok hangon I'll tweak your code and show you what I mean...

**Comment by andymeneely** [comment]
Actually I think if you just do `Icon#{i + 1}.svg` then the file should be there. Or rename your files starting at 0.

**Comment by JKochosky** [comment]
Okay... I added the file names/x-y coords to the layout configurations, and modified the ranges code to this:

```
tolerance = data['Tolerance']
1.upto(4).each do |n|
  range = tolerance.each_index.select { |i| tolerance[i] == n}
  n.times do |i|
    svg layout: "Icon#{i + 1}"
  end
end
```
And boy, does it blow up good!
```
internal buffer error : Memory allocation failed : growing buffer
internal buffer error : Memory allocation failed : growing buffer
rake aborted!
RSVG::Error::Failed: Error parsing XML data
Beer_Batter.rb:62:in `block (3 levels) in <top (required)>'
Beer_Batter.rb:61:in `times'
Beer_Batter.rb:61:in `block (2 levels) in <top (required)>'
Beer_Batter.rb:59:in `upto'
Beer_Batter.rb:59:in `each'
Beer_Batter.rb:59:in `block in <top (required)>'
Beer_Batter.rb:7:in `new'
Beer_Batter.rb:7:in `<top (required)>'
E:/Creepy Bunny/Beer Batter/Rakefile:19:in `load'
E:/Creepy Bunny/Beer Batter/Rakefile:19:in `block in <top (required)>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by andymeneely** [comment]
Nice error!! Yeah my x-y stuff in the layouts was before I understood that you were doing multiple icons based on the number.

I would put the x-y stuff back into your svg call since we're computing based on `i`

Now... the RSVG error might be a problem with your SVG file. Can you draw the file directly without this other fanciness? Because the only XML we're dealing with here is your svg file.

Admittedly this multiple-icons-per-number is a tricky case but a common one in prototyping. I wonder if there's a useful construct we can create around this to make it easier on folks. If you had a special method to make this look cleaner, what would it be? (@bcompter or @programmingisgood feel free to weigh in on this too).

**Comment by JKochosky** [comment]
If I replace this with calls to just draw each of the 4 icons (keeping the file names in the layout), they all draw just fine, so it's now becoming a method of trying to get the `svg layout: "Icon#{i + 1}"` to iterate.

As for a method for this, rather than trying to iterate a loop?  Maybe supplying an array of the icon filenames, and then the method drawing the first **x** elements in the array.

**Comment by yipcma** [comment]
i face a similar issue, in my case from a csv, i need certain icons when there is value in the column, but do not need icon when the value is '', but i haven't found a way to do that. A silly way would be to set opacity based on variable value, but i hope there's a more elegant way to do this. Simply put, how do i toggle svg based on value in an array?

**Comment by andymeneely** [comment]
The  `svg data: nil, file: nil` field will not do anything. Or, more specifically:

```ruby
svg data: [mysvgxmlstring, nil, mysvgxmlstring] # draws whatever is in mysvgxmlstring on the first and third card, but not the second
```
Alternatively, you can use the `range` option to set only what you want:

```
svg data: mysvgxmlstring # draws whatever is in mysvgxmlstring on the first and third card, but not the second
```

So to refactor what you have, just replace nil with that first game_icons call:

```ruby
svg data: deck['VP'].map do |i| 
	if i
	  nil
	else 
		GameIcons.get(:cash).recolor(fg: '000', bg: 'fff', fg_opacity: 0, bg_opacity: 0).string}, layout: :vp_icon
	end
end
```

**Comment by yipcma** [comment]
nice it works :)
