### ISSUE TITLE
option to align text baseline or bottom instead of just top

### ISSUE THREAD

**Issue by sparr** [andymeneely/squib#202]
Currently the y coordinate of text specifies the top edge of the bounding box of the text. It would be useful if we could optionally specify where we want the baseline of the text or the bottom edge of the bounding box instead, so that text could be placed directly above a line or other graphical element without having to specify how tall the glyphs are.

**Comment by andymeneely** [comment]
Have you looked at valign? If you set the height and make the box tall
enough, you'll get the same effect.

**Comment by sparr** [comment]
a tall box and valign bottom can let me place the bottom of the bounding box, but requires extra arithmetic. I don't think placing the baseline of the text is possible at all currently.

**Comment by andymeneely** [comment]
Yeah, related to your stackoverflow question - I don't think I'd be able to
set the baseline that way since I won't know the size of the bounding box
unless otherwise specified. When I run into this problem myself, I end up
doing extra arithmetic to make it work.

I'm keeping this request open, however, because, like you, I'm not a fan of
doing arithmetic in my head. Maybe someone will think of a better way.

**Comment by sparr** [comment]
I haven't looked at the code in question yet, but I suspect that currently pango is rendering text directly onto the image? Maybe what could happen is the render could happen into a buffer, and we get info from pango about the rendered text like the location of the baseline, then we composite the buffer onto the image with an appropriate y offset.

More investigation required on my part, when I care enough to make this work :)

**Comment by andymeneely** [comment]
Yeah I'll look into it too. I think there's a way to just do an "update layout" without actually doing the drawing.

On the Squib front end side, how would you expect the syntax to look?

**Comment by sparr** [comment]
as an option to `text`

`vsomething: [top|cap|base|bottom|any other vertical landmark exposed by pango]`

**Comment by sparr** [comment]
also, closely tied to this, hsomething or vsomething could take middle (or various different middles) so that the x or y coord would be the middle of the text.

currently to center text in a vertical space you have to give the bounding box a defined height, which precludes vertical centering combined with `hint` outlines or use of `extents` to do fancier things around the text.

**Comment by sparr** [comment]
`hanchor` and `vanchor` come to mind. you are anchoring a specific part of the text box to the given coordinate
