### ISSUE TITLE
save_sheet option to reverse row direction for double sided printing

### ISSUE THREAD

**Issue by sparr** [andymeneely/squib#204]
I've got one `Deck` for the front of my cards and one for the back. I'd like to be able to `save_sheet` the second deck with the cards being tiled right to left instead of left to right (still top to bottom). This would allow duplex printing to produce cuttable cards with no additional manipulation.

**Comment by andymeneely** [comment]
Agreed. #93 and #133 we've talked about handling backs better. For now, if we can work toward #217 and do some `range` fanciness, that can hold us over until we can get backsides.

**Comment by sparr** [comment]
#217 would need to more extension on top of what's currently suggested there to make duplex printing work, unless the sheet template also contains code for alternating orders.

#208 stands alone as a functional solution to the problem, and lets users print duplex sheets *today*

**Comment by sparr** [comment]
#208 merged
