### ISSUE TITLE
Could a polyline be possible?

### ISSUE THREAD

**Issue by sparr** [andymeneely/squib#210]
If there was a primitive for a polyline, it would probably need to take an array of coordinates. That would mean that putting a different polyline on each card in a deck would be an array of arrays, and just having an array wouldn't mean the same thing as it means for all the other primitives.

Is this something the DSL parsing can handle? If you can point me in the right direction, I'd like to try implementing it.

**Comment by andymeneely** [comment]
This can be done in Cairo, but I chose not to do it for simplicity. I figured that if you're gonna start coding polylines you might as well use SVG. Have you tried going that route?

**Comment by sparr** [comment]
My immediate goal with a polyline was to represent more complex cut and safe lines on default layouts. However, given that some of them also include curves, that would require a very capable "polyline" that can handle splines and arcs.

I think #212 might be a better approach for this, defining cut-rect-1 cut-circle-2 etc separately then looping over them.

I'd still like a polyline eventually, but it's less pressing than it might have been.
