### ISSUE TITLE
bad redirect on github.io

### ISSUE THREAD

**Issue by sparr** [andymeneely/squib#216]
andymeneely.github.io/squib/doc redirects to http://squib.rocks/doc which is dead. Either the github.io redirect should go to squib.readthedocs.io or there should be a new redirect at squib.rocks/doc to that destination.

**Comment by andymeneely** [comment]
Is there somewhere that links to andymeneely.github.io/squib/doc? I was never able to find that.

**Comment by sparr** [comment]
https://github.com/andymeneely/squib/issues/100
https://boardgamegeek.com/article/20002847#20002847
https://www.reddit.com/r/boardgames/comments/3bhx52/squib_a_ruby_dsl_for_prototyping_card_games/csmg3wl/
etc

I suspect the authoritative site that contained the link has long since disappeared, but a lot of people copied those links and posted elsewhere.

**Comment by andymeneely** [comment]
Ah, yeah I suppose I should maintain a forward then.
