### ISSUE TITLE
We need better stack/back traces

### ISSUE THREAD

**Issue by sparr** [andymeneely/squib#218]
Here's a stack trace recently posted to the BGG forum thread, which illustrates a problem I've encountered numerous times as well:

```
/gems/squib-0.13.2/lib/squib/layout_parser.rb:84:in `has_extends?': undefined method `key?' for "auto-repair.svg":String (NoMethodError)
[snip]
from /gems/squib-0.13.2/lib/squib/layout_parser.rb:17:in `load_layout'
from /gems/squib-0.13.2/lib/squib/deck.rb:71:in `initialize'
from _part2_01_factions.rb:6:in `new'
from _part2_01_factions.rb:6:in `<main>'
```

The problem here is that `_part2_01_factions.rb` line 6 is a call to Deck.new which, as usual, includes a code block. The actual problem is somewhere in that code block, but the user is given no indication where.

I don't know if this is a limitation of Ruby, or if there's some way we could be asking for or providing more useful backtraces.

PS: We should also address all the places in the DSL where bare ruby code exceptions are raised instead of graceful error handling, but that's another issue (or another hundred).

**Comment by andymeneely** [comment]
Yeah we can definitely do better error checking on the layout parser since a lot can go wrong with those. For better error handling in general sometimes there isn't really a general solution. But this is one place that we could improve.
