### ISSUE TITLE
error in getting started guide

### ISSUE THREAD

**Issue by sparr** [andymeneely/squib#220]
https://gist.github.com/andymeneely/d2bb2eb028b27cf1dace#file-_part2_03_illustrations_m2-rb

Original:
`svg file: data['title'].map { |t| "#{t.downcase}.svg"}, # method 2`

Should be:
`svg file: data['name'].map { |t| "#{t.downcase}.svg"}, # method 2`

originally reported by BGG user matfe https://boardgamegeek.com/article/25317620#25317620

PS: that gist should probably also have a name other than ".gitignore"

**Comment by andymeneely** [comment]
Fixed. Although I cannot for the life of me figure out how to change that .gitignore name.
