### ISSUE TITLE
Unclear error message reading invalid svg file

### ISSUE THREAD

**Issue by daveschaefer** [andymeneely/squib#228]
I had a png that was incorrectly saved with an '.svg' extension. When squib attempted to read the file it gave a not very clear error message like this:

    Error domain 1 code 4 on line 1 column 1 of data: Document is empty

Is this something we'd be interested in improving? I'll post a proposed patch shortly.

**Repro Steps:**

* Save a file that's not a valid .svg with an .svg extension
* Attempt to read the file with `svg file:`

**Comment by andymeneely** [comment]
Thanks again for this! It'll be in the next release coming soon.
