### ISSUE TITLE
Make a set of Atom snippets

### ISSUE THREAD

**Issue by andymeneely** [andymeneely/squib#230]
Over the last year I've moved from Sublime to Atom, so I'd like to do some sort of support for that. Snippets are a good start. We can port what we have from the SublimeText plugin and then add whatever we need.

**Comment by rnewton** [comment]
Hey, @andymeneely, I've set up a [repository](https://github.com/rnewton/atom-squib) and published the package to the [atom registry](https://atom.io/packages/atom-squib). Enjoy!

**Comment by andymeneely** [comment]
Wohoo!!

**Comment by andymeneely** [comment]
I'll make sure I put this into the README too before the upcoming release.
