### ISSUE TITLE
Text and code for text wrap options are not the same

### ISSUE THREAD

**Issue by bbugh** [andymeneely/squib#237]
The text documentation and code for `text wrap: ?` don't line up. 

In [the code for text/wrap](https://github.com/andymeneely/squib/blob/dfedad0fed99fe8b40eb931dc3b513a8cff1b0b1/lib/squib/args/paragraph.rb), the argumenst are validated as `'wrap must be one of: word, char, word_char, true, or false'`

In [the docs for text/wrap](https://github.com/andymeneely/squib/blob/dfedad0fed99fe8b40eb931dc3b513a8cff1b0b1/docs/dsl/text.rst), it's stated as: Options are ``:none``, ``:word``, ``:char``, ``:word_char``. Also: ``true`` is the same as ``:word_char``, ``false`` is the same as ``:none``

🎶 *One of these things is not like the others...* 🎶

I looked at Pango and it doesn't have a wrap option for `none`. There doesn't appear to be a way to turn off word wrap, so I imagine that the documentation is incorrect.

**Comment by andymeneely** [comment]
Fixed! (finally...)
