### ISSUE TITLE
Install issues on Mac and Linux

### ISSUE THREAD

**Issue by drpepper** [andymeneely/squib#242]
Hi, I'm really excited about using Squib but have been banging my head against the wall trying to install it. I'm hoping the solution is obvious to Ruby people...

I first tried to install it directly on my mac, using Homebrew for dependencies. The `gem install squib` keeps erroring out each time it needs a "native" dependency (perhaps because I needed to run ruby with sudo, which Homebrew doesn't like?). So each time I installed by hand using Homebrew. 

Anyway, it now gives errors like this: 
```
(null)-WARNING **: Failed to load shared library 'libcairo-gobject.2.dylib' referenced by the typelib: dlopen(libcairo-gobject.2.dylib, 0x0009): file not found 'libcairo-gobject.2.dylib'
	from /Library/Ruby/Gems/2.3.0/gems/gobject-introspection-3.1.9/lib/gobject-introspection/arg-info.rb:31:in `compute_gclosure?'
...
``` 

I tried playing around with `DYLD_FALLBACK_LIBRARY_PATH` but it didn't seem to change anything. So... I gave up and tried installing Squib on a virtual Linux box with Vagrant, thinking that the dependencies would be easier to manage.

But not really- `gem install squib` kept erroring with each native extension (libcairo2-dev libgirepository1.0-dev libpango1.0-dev libgdk-pixbuf2.0-dev librsvg2-dev). This time I installed them using apt-get. After finishing, I get an error with `rsvg2` that I can't make any sense of.

```
/home/vagrant/.rvm/gems/ruby-2.4.1/gems/rsvg2-3.1.9/lib/rsvg2/version.rb:19:in `<module:Version>': uninitialized constant Rsvg::Version::MAJOR_VERSION (NameError)
```

Could anyone help, please?

**Comment by drpepper** [comment]
Ok - I got it to work on a newer version of Linux (16.04) using Vagrant (ubuntu/xenial64).

First I installed Ruby and build tools (`apt-get install build-essential ruby-dev`). 

When squib, there was an error building `gdk_pixbuf2-3.1.9.gem` about missing `/usr/share/rubygems-integration/all/gems/rake-10.5.0/bin/rake`. Following [this StackOverflow post](https://stackoverflow.com/a/45928418) I created the missing symbolic link and installed again. 

```
sudo mkdir -p /usr/share/rubygems-integration/all/gems/rake-10.5.0/bin/
sudo ln -s /usr/bin/rake /usr/share/rubygems-integration/all/gems/rake-10.5.0/bin/rake
sudo gem install squib
``` 

And it worked! I would suggest adding something about this to the getting started documentation...

**Comment by andymeneely** [comment]
Glad you got it figured out! Yeah the Mac stuff is a moving target - on some setups everything works fine, other times it'll be less consistent. I'll make a link to this from the wiki. 

Looking at it now I can't reproduce it on my Mac, so it might not be a widespread issue. But, glad we've got it documented!
