### ISSUE TITLE
svg data: gameicons not working properly for excel?

### ISSUE THREAD

**Issue by TasmaniaKrama** [andymeneely/squib#243]
Just as we can pull text data from excel like so
`text str: deck['Power'], layout: :PowerText`
why can't we simply use this code which works:
`svg data: GameIcons.get("ak47").
                    recolor(fg: '000000', bg: 'FFFFFF').
                    string, layout: :GovIcon`
and change it to
`svg data: GameIcons.get(deck['Power']).
                    recolor(fg: '000000', bg: 'FFFFFF').
                    string, layout: :GovIcon`
and pull the ak47 icon from the excel column called Power.
Am I missing something here?

**Comment by andymeneely** [comment]
Sorry I missed this for so long! 

This has nothing to do with Excel or GameIcons - it's how Squib handles inputs. (See [Squib Thinks in Arrays](http://squib.readthedocs.io/en/v0.14.0/arrays.html)). 

So when `svg data: 'string'`, it will apply `'string'` to every single card. When you give `deck['Power']` - that's an array.

Now, if you want to map the Power column to various GameIcon recolorings, or even various GameIcons, you can do that like this:

```
# I'm assuming you have powers in your Excel sheet called 'melee' and 'ranged'
deck['PowerIcon'] = deck['Power'].map do |power|
  case power
  when 'ranged'
    GameIcons.get("ak47").recolor(fg: '000000', bg: 'FFFFFF').string
  when 'melee'
    GameIcons.get("lorc/fist").recolor(fg: '000000', bg: 'FFFFFF').string
  end 
end
  
svg data: deck['PowerIcon']
```

(Note: I haven't tested this code - so it might need some attention if you copy-paste)
