### ISSUE TITLE
'circle' method adds line

### ISSUE THREAD

**Issue by hewhocutsdown** [andymeneely/squib#248]
When creating a circle using the code below, the following line gets created as well.

![card_32](https://user-images.githubusercontent.com/613613/43269217-03a6224c-90b8-11e8-8571-818df3755345.png)

`circle x: 410, y: 1000, radius: 25, fill_color: '#CCCCCC'`

**Comment by andymeneely** [comment]
Interesting. I'll take a look. In the meantime you can work around it by doing an svg

**Comment by hewhocutsdown** [comment]
![paradigm a scenario 1_04](https://user-images.githubusercontent.com/613613/43358787-ebdb7f62-925c-11e8-97cb-2ec63c5c5a7b.png)

another example:

circle x: 100, y: 300, radius: 60, fill_color: '#e6e6e6', stroke_color: 'red', stroke_width: 4

**Comment by andymeneely** [comment]
I can't seem to reproduce this - can you show me the lines before and after your `circle` call?

**Comment by hewhocutsdown** [comment]
here's the whole deck.rb

https://gist.github.com/hewhocutsdown/710e2f9aa555e4e1a5c67e6f6bdeb0a5

**Comment by andymeneely** [comment]
Fix for this will be in 0.14.2 - coming out soon.

Looks like recent Pango updates forgot to reset their path operators. So I made sure that we do it every time.

**Comment by hewhocutsdown** [comment]
Awesome, thanks
