### ISSUE TITLE
Can't get the 'squib' command working at CLI

### ISSUE THREAD

**Issue by zurfarosa** [andymeneely/squib#252]
Sorry, new to both Ruby and Squib!

I have installed Ruby using Homebrew, and then installed Squib via `gem install`.

Although Squib appears to be working fine when I play around with it in `irb`, I can't get the `squib` command to work at the command line:

```
Users-Air:~ zurfarosa$ squib new arctic-lemming
-bash: squib: command not found
```

Can anyone help?

**Comment by zurfarosa** [comment]
Apologies, I've resolved the issue. I fixed  my PATH in ~/.bash_profile. It now reads: 

`export PATH=/usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/bin:$PATH
`

**Comment by andymeneely** [comment]
Awesome! Glad you figured it out. Feel free to come back next time you need help!
