### ISSUE TITLE
Feature Request: Set Default Value for Text

### ISSUE THREAD

**Issue by CovertDad** [andymeneely/squib#255]
It would be really cool if the text command had a default value parameter.  I.e., I've got a dataset that has empty rows on a numerical column, and when I use the text command, if the value of a particular row is null, then text fills in 0.

**Comment by andymeneely** [comment]
The default for `text` is the empty string. Converting to zero is probably happening based on how it's coming in from the dataset. 

To set the default, just put it in the layout file under `str`

**Comment by andymeneely** [comment]
Also, xlsx (and I think csv) have the ability to pass a block in that allows you to preprocess the data. Here's an example: https://github.com/andymeneely/squib/blob/master/samples/data/_excel.rb#L40-L47

So yours might be something like:
```ruby
resource_data = Squib.xlsx(file: 'sample.xlsx') do |header, value|
  if value==0
    "default value for zero!"
  else
    value
  end
end
```

**Comment by CovertDad** [comment]
I don't think I made what I was asking for very clear.  Let me try to explain better:

Say my data file is like so:
```
|A|B|C|
| |1|1|
|1| |1|
|2|3|2|
```

What I'm asking for is something like the valueifempty parameter here:

```
text(str: str, valueifempty: '0', font: 'Charter Roman 40', 
       layout: 'text_spot', ellipsize: false, justify: false) do |embed|
    Embedding(embed)
  end
```
Which would output:
```
|A|B|C|
|0|1|1|
|1|0|1|
|2|3|2|
```

Where the valueifempty replaces the value of str if it's null or empty.

**Comment by andymeneely** [comment]
Instead of adding a new feature, though, I think there are other ways to accomplish it cleanly. Here's another way:

Instead of using `str`, I'll call the data `a_values` to represent column A from your data.

```ruby
text str: a_values.map { |a| a.to_s.empty? ? 0 : a }
```

The ruby `map` operation on the array of strings will apply that block of code to every element and create a new array. 

So with the above option or the pre-processing option, I think there are enough tools to get it done without a new feature.

**Comment by CovertDad** [comment]
Fair enough.  So, being a neophyte ruby programmer, how would I get the values from the CSV into a_values?

```
data = Squib.csv file: 'cards.csv'
a_values = data['A']
```
Am I even close?

**Comment by andymeneely** [comment]
Spot on. 

Better yet, because [columns become methods](https://squib.readthedocs.io/en/v0.14.0/dsl/data_frame.html#columns-become-methods), you can even do `data.a`.
