### ISSUE TITLE
Local dev server to see changes immediatly

### ISSUE THREAD

**Issue by johannes-z** [andymeneely/squib#258]
As the title says, a local dev server that serves the output on a simple webpage would be great for development, to see changes immediatly when you change any of the files used by `deck.rb`. https://github.com/ghostsquad/pycard/ for example has this built in.

**Comment by andymeneely** [comment]
You can already do this Guard: https://squib.readthedocs.io/en/v0.14.0/guides/guard.html

I use Guard with Squib all the time. You can see my example Guardfile here: https://github.com/andymeneely/project-timber-wolf/blob/master/Guardfile

**Comment by andymeneely** [comment]
Oh and additionally - I use Atom and their image viewer updates automatically on a new build.

**Comment by andymeneely** [comment]
Let me know how Guard works out for you. I'm closing this unless there's anything else to discuss.
