### ISSUE TITLE
Problem with text formatting

### ISSUE THREAD

**Issue by SquigVicious** [andymeneely/squib#261]
Hello,

I have a problem with my script converting uncommonly used characters and am wondering how to remedy the situation. One of my foes is called the Abúhukü. The text looks fine in the CSV, so it's not an export error. When I build the cards though, the output on the card is converting these characters to dice? - I'll attach a link here:

https://i.imgur.com/R2R41cF.png

Is this a pango markup error? I've tried converting the special characters to unicode/html but that doesn't seem to work - it just prints out the text codes instead of the letters.

Any ideas? Thanks in advance for any assistance you can provide.

Jason
(cross-posted on bgg guild page as well).

**Comment by andymeneely** [comment]
It's not dice, it's a unicode error where it can't find the character. I've run into this. Could be a couple of things.

* Check that the font with those characters is properly installed on your system
* Check that you are referencing the font correctly in Squib. Sometimes font names with spaces in them require a comma (depending on the os)
* Are you doing image embedding on this string? If you add a `text` call that does NOT use image embedding using that font BEFORE you do that call, it might go away. 

I've also filed bug reports on how Pango handles multibyte characters, hopefully this isn't one of those situations.

**Comment by SquigVicious** [comment]
Thanks Andy,

The font I am using does have a comma after it (it was Poison Hope, 18), which is being set in the layout file. I changed that font to Arial (which I know has those characters), rebuilt the cards and it displayed the word like this:

![image](https://user-images.githubusercontent.com/39200558/51501322-414e8980-1d86-11e9-8e1c-b19ea1c900f3.png)

Additionally, I am not doing any image embedding. Here is the line from the .rb
  text str: data['Name'],                    layout: 'title_txt'

Anything else I could look into or try?

**Comment by SquigVicious** [comment]
As a test, I just overwrote the data reference with "Abúhukü" and it displayed the string correctly on the cards. Obviously this solution won't work though as I want each card to use the title in data.

  text str: "Abúhukü",                    layout: 'title_txt'

**Comment by andymeneely** [comment]
Hm. Interesting. Let me try to reproduce.

**Comment by andymeneely** [comment]
Oh - and you're pulling directly from CSV, not from Excel?

**Comment by SquigVicious** [comment]
Yeah, pulling from a CSV created by Google Sheets. Not sure if there are any differences there, but just want to be thorough in my explanation. :)

**Comment by andymeneely** [comment]
Ok here's a workaround and I'll make Squib's CSV more sane for the next release. Turns out Ruby is auto-detecting the text encoding with CSV, and this sequence of characters happen to look like IBM437 and not UTF-8. That being said, character sets are hard. [This is one of my favorite articles on them](https://www.joelonsoftware.com/2003/10/08/the-absolute-minimum-every-software-developer-absolutely-positively-must-know-about-unicode-and-character-sets-no-excuses/) in case anyone wants to read up. Anyhoo, here's the workaround: 

```ruby
data = Squib.csv data: File.read('yourdata.csv').force_encoding('UTF-8') 
```

For posterity, here's my test case with various attempts:

```ruby
require 'squib'

data = Squib.csv file: "bug261.csv" # This fails
data2 = Squib.csv data: "Name\nAbúhukü" # This works, because Ruby source is UTF-8
data3 = Squib.csv file: 'bug261.csv', encoding: Encoding::UTF_8 #won't work, but should??
data4 = Squib.csv data: File.read('bug261.csv').force_encoding('UTF-8') #works!

Squib::Deck.new do
  background color: :white

  text str: "Abúhukü", font: 'Arial', y: 100
  text str: data['Name']
  text str: data2['Name'], font: 'Arial', y: 200
  text str: data3['Name'], font: 'Arial', y: 300
  text str: data4['Name'], font: 'Arial', y: 400

  save prefix: 'bug_261_', format: :png
end
```

**Comment by SquigVicious** [comment]
Andy, you are awesome! Thank you so much for investigating and finding a solve for this. I really appreciate it.

**Comment by andymeneely** [comment]
Glad to help! Let me know what else you'd like to see in Squib in the future. Don't be a stranger :)
