### ISSUE TITLE
Lowercase `qty` doesn't work as an `explode` default, contrary to docs

### ISSUE THREAD

**Issue by iancboswell** [andymeneely/squib#262]
First of all, Squib is a wonderful tool. Thanks much for your hard work.

I ran into an issue where the `qty` column in my deck's CSV was being ignored, despite documentation claiming it's the default for `explode`: https://squib.readthedocs.io/en/v0.14.0/dsl/csv.html?highlight=qty

I then checked the examples and saw that the Q was capitalized. That fixed the problem. However, the docs ought to reflect that, or Squib ought to tolerate lowercase here.

**Comment by andymeneely** [comment]
Good catch! I’ll fix the docs. In general all parameters are lower case. 

And thank you for the kind words!
