### ISSUE TITLE
Translucent text overlay

### ISSUE THREAD

**Issue by peterusev** [andymeneely/squib#265]
Is it possible to create a translucent text overlay on an image similar to the [example here](https://www.w3schools.com/howto/howto_css_image_text_blocks.asp)?

**Comment by peterusev** [comment]
Was able to solve this by doing the following:

text_container:
  width: 540
  height: 40
  fill_color: '#33333399' # https://gist.github.com/lopspower/03fb1cc0ac9f32ef38f4
  stroke_width: 0
text:
  extends: text_container
  align: center
  valign: middle
  font_size: 6
  color: '#DDD'

**Comment by andymeneely** [comment]
Yup! That's how you do it.
