### ISSUE TITLE
Derive individual filenames from a field

### ISSUE THREAD

**Issue by undercoverdesigns** [andymeneely/squib#268]
It would be very nice if, when saving output to individual files, I could specify a field from the data to use for the file name, rather than only being able to name with some prefix and an incrementing counter.

**Comment by andymeneely** [comment]
I like it! I think we can manage that.

Starting today, I've got some bandwidth to work on Squib, so your timing is perfect.

**Comment by andymeneely** [comment]
Oh you can already do this. The "prefix" already supports arrays. And if you set `count_format` to the empty string it'll just not include it.

I'm writing a sample to show this. Here's an abbreviated version:

```ruby
require 'squib'

Squib::Deck.new(width: 50, height: 50, cards: 2) do
  background color: :white
  text str: (0..16).to_a, font: 'Arial Bold 12'

  # thief.png
  # thug.png
  data = csv data: "filename\nthief\nthug"
  save_png prefix: data.filename, count_format: ''
end
```

That being said, I should probably just rename "count_format" to "suffix". You can really put as many of those formatting directives as you want in both prefix or count_format.

**Comment by andymeneely** [comment]
Here the larger sample: 

```ruby
require 'squib'

# This demonstrates the many ways you can save file to save_png and the like
Squib::Deck.new(width: 50, height: 50, cards: 2) do
  background color: :white
  text str: (0..16).to_a, font: 'Arial Bold 12'

  # three digits, e.g. save_three_digits_000.png
  save_png prefix: 'save_three_digits_', count_format: '%03d'

  # foo_0.png
  # bar_1.png
  save_png prefix: ['foo_', 'bar_'], count_format: '%01d'

  # foo.png
  # bar.png
  save_png prefix: ['foo', 'bar'], count_format: ''

  # thief.png
  # thug.png
  data = csv data: "filename\nthief\nthug"
  save_png prefix: data.filename, count_format: ''

end

```
