### ISSUE TITLE
Possible wrong default value in docs for trim radius?

### ISSUE THREAD

**Issue by Karneades** [andymeneely/squib#270]
Hi

When using save_png with default values no trim radius is used, when using save_pdf with default values I get a trim radius in the corners. Overwriting trim_radius to 0 when using save_pdf removes it.

I'm not sure if the docs should be updated or I misunderstand some options :)

In the [docs](https://github.com/andymeneely/squib/blob/f83419defcab1dea35005ace981ced597807eb94/docs/dsl/save_pdf.rst) we have the following we have the default value of 0.

In the save sheet method I see a trim_radius of 38 - could that be the default value which contradicts with the docs?

https://github.com/andymeneely/squib/blob/f83419defcab1dea35005ace981ced597807eb94/lib/squib/args/sheet.rb#L42

The save batch method sets it to 0

https://github.com/andymeneely/squib/blob/f83419defcab1dea35005ace981ced597807eb94/lib/squib/args/save_batch.rb#L21

**Comment by andymeneely** [comment]
Good catch. I think 0 is a better default, so it'll default to 0 in the next release.

**Comment by Karneades** [comment]
Thanks for your fast reply and change!

**Comment by andymeneely** [comment]
Keep 'em comin!
