### ISSUE TITLE
SVG game-icon with shadow effect loses foreground color.

### ISSUE THREAD

**Issue by YoungWillem** [andymeneely/squib#282]
You can add a shadow (or glow) effect with the studio on game-icons.net. When you download the icon as an SVG and have Squib display it, the foreground color is reset to white.

If you open the attached SVG in your image viewer or browser, you will see the foreground color is yellow. When I run "svg file: 'test2.svg', x: 200, y: 200, height: 400, width: 400" in Squib, the foreground color in the output file is white (see attached PNG file).

[test2.zip](https://github.com/andymeneely/squib/files/3469330/test2.zip)

I am running Squib version 0.14.2 on Windows 10.

**Comment by andymeneely** [comment]
Ah - I believe librsvg doesn't support all of the `<filter>` effects. You might be out of luck on that one. If you open it in Inkscape and then apply the effect directly, you can still get the shadows. I'll double-check their fancy filter coverage.

**Comment by andymeneely** [comment]
Hm. Is it suppose to be yellow with a white shadow? This was generated by this squib script:

```ruby 
require 'squib'

Squib::Deck.new do
  svg file: 'test2.svg', x: 200, y: 200, height: 400, width: 400

  save_png
end

```
![card_00](https://user-images.githubusercontent.com/341847/62494673-06e88f00-b7a2-11e9-8f24-eb4f7fc190ec.png)

**Comment by YoungWillem** [comment]
That is indeed what it's supposed to look like! However, copy/pasting your script exactly still gives me this output:
![card_00](https://user-images.githubusercontent.com/26960505/62514153-96cc1e80-b81e-11e9-88f2-029a17441eb0.png)

It is already good to know that Squib can handle the shadow after all. Would you have any idea what could be going wrong on my end?

**Comment by andymeneely** [comment]
Ah - when I used Squib v0.14.2 (latest production release) the bad behavior came back. So librsvg must have fixed this in the last year. I'll push out a new release of Squib today and that should fix it. Been meaning to do that anyway.

**Comment by YoungWillem** [comment]
Super, thank you for looking into this, Andy!

**Comment by andymeneely** [comment]
Absolutely! Thanks for filing the bug. New version is out - let me know if it works for you.

**Comment by YoungWillem** [comment]
Yup, this works as expected now!
