### ISSUE TITLE
Having troubles installing 

### ISSUE THREAD

**Issue by ravenwolf16** [andymeneely/squib#287]
I have tried reinstalling the dev kit and ruby itself, I have tried installing gems that squib requires on their own and that did not work

Here is the error output I keep getting and i can not make heads or tails of what is wrong
https://pastebin.com/cvcBvsd0

**Comment by andymeneely** [comment]
Which gem does this fail on? Can you show me the full output of `gem install`?

The gem output is from the devkit trying to compile one of Squib's dependencies with some C code. 

At the moment I'm using Ruby 2.5.3p105 on Windows - that's another possibility to try. In the meantime I'll try out Ruby 2.6 on Windows and see what happens. It does install fine on our build server, though.

**Comment by ravenwolf16** [comment]
Here is a paste of what i get when i tried installing squib. 
Fresh install of ruby + devkit 2.6 once more

**Comment by andymeneely** [comment]
Ah ok, yep. I can reproduce it too. Looks like it's pkg-config, which they recently had a problem with. Working on it.

**Comment by andymeneely** [comment]
Alright - looks like they fixed it in a release that came out Oct 10. I updated the dependencies and that should fix the issue. If you do `gem install squib` again and get version `0.15.3`, that should fix it.

**Comment by ravenwolf16** [comment]
Awesome thank you I'll try and get it to work.

**Comment by ravenwolf16** [comment]
It worked now thank you again
