### ISSUE TITLE
font size is dramatically different between computers

### ISSUE THREAD

**Issue by jrogozen** [andymeneely/squib#293]
hi,

is the font size set to be pixels by default?

e.g yaml file

```
my_text:
  font: Arial, bold 10
```

would equal 10px arial bold?

on one of my computers, the rendered text shows up as a HUGE font (definitely not 10px). i set all the font sizes to ranges from 4-10, and they appeared in the generated png in the correct position and a valid sizing.

however, when working with my codebase on another computer, the generated png does seem to be using px sizing and converts "10" to a tiny font size. to get the same generated size as my first computer, i'd have to change the above to something like

```
my_text:
  font: Arial, bold 36
```

both computers are running mac os x, and have the same font files.

thanks! (love this tool btw)

**Comment by andymeneely** [comment]
Hm. We changed the way we do font sizes a few releases back - do you have the latest squib on both?

**Comment by jrogozen** [comment]
I've tried fresh installs for both of them, gemfile.lock is showing 

```
squib (0.15.3)
      cairo (~> 1.16)
      classy_hash (= 0.2.1)
      gio2 (~> 3.4)
      gobject-introspection (~> 3.4)
      highline (= 2.0.2)
      mercenary (= 0.3.6)
      nokogiri (= 1.10.4)
      pango (~> 3.4)
      roo (= 2.8.2)
      rsvg2 (~> 3.4)
      ruby-progressbar (~> 1.10)
```

**Comment by andymeneely** [comment]
Perhaps the underlying Pango library is old on one machine. Are you using homebrew? Maybe update there? In each Squib, print the value of `Pango.version_string`. Mine is 1.44.7

I also assume you know *for sure* that the code is the same across both.

**Comment by andymeneely** [comment]
Oh and also: remove old versions of Squib too with `gem cleanup`. If you run with that Gemfile and do `bundle exec ruby deck.rb` on both is it still different?

**Comment by jrogozen** [comment]
the pango version was exactly it :). upgraded to 1.44.7 and now the font sizing is consistent. thanks so much!
