### ISSUE TITLE
Windows installation fails

### ISSUE THREAD

**Issue by nickolasreynolds** [andymeneely/squib#309]
I'm trying to `gem install squib` on a Windows box and it just keeps failing over and over again. It doesn't matter what version of Ruby I install, it doesn't matter if I uninstall and delete everything, reboot, and do a fresh install, it doesn't matter if I have admin privileges or not, etc. This is the error I'm seeing:

```
Failed to run 'pacman.exe -S --noconfirm mingw-w64-x86_64-cairo'.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby26-x64/bin/$(RUBY_BASE_NAME)
        --with-pkg-config
        --without-pkg-config
        --with-override-variables
        --without-override-variables

To see why this extension failed to compile, please check the mkmf.log which can be found here:
```

I'm a bit out of my depth here trying to chase down why RubyGems (ostensibly a package manager that's supposed to handle all of this stuff automatically) refuses to install a gem. Any suggestions?

**Comment by andymeneely** [comment]
Ugh. Yeah I've been dealing with this myself lately. Try switching from Ruby 2.7 to Ruby 2.6 if you can.

Looks like the problem was with Cairo. They might have broken something with a recent release or something - I'll chase it down.

**Comment by andymeneely** [comment]
Oh and BTW, just to interpret this FTR for anyone else coming across this, what's happening here is that when we install the Cairo gem (our graphics engine) it needs to compile the library in C on your Windows platform. They call these C compilers "devkit" on [RubyInstaller](https://rubyinstaller.org/downloads/), and everything *should* be packaged in a way that the gem will compile when you get it. The RubyInstaller folks use MSYS2 to compile things, and if that's not set up properly (or at all) then things get lost. That's what "pacman" is - it's the MSYS2 package manager. 

I personally do most of my Squib work on Windows, so usually I catch these immediately. Not sure what's going on here just yet.

**Comment by nickolasreynolds** [comment]
Ok, the combination of downgrading to 2.6 _and_ doing the DevKit installation worked! This is the exact version I installed: https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-2.6.6-1/rubyinstaller-devkit-2.6.6-1-x64.exe
