### ISSUE TITLE
Switch from `prefix:` to format string

### ISSUE THREAD

**Issue by andymeneely** [andymeneely/squib#31]
Should be easy once the new `Args` architecture is in place. The `prefix` arg for saving files is a bit lame. Perhaps a format string is better. Something like 

```ruby
'%02d.png' % card_num #e.g. 
```

**Comment by scraimer** [comment]
Whooo!

**Comment by andymeneely** [comment]
Done in 4ecbaa4e31561c81c51a9299f7e85a57dc17d204
