### ISSUE TITLE
Link to samples is broken

### ISSUE THREAD

**Issue by andrewhavens** [andymeneely/squib#312]
Hello! This looks like a really cool project! I just came across your website and clicked on the samples link and discovered it was broken. I thought I would mention it just in case you didn't know.

At the bottom of https://squib.rocks it says "The above examples can be found here." and links to https://github.com/andymeneely/squib/tree/gh-pages/squib_examples which results in a 404.

**Comment by andymeneely** [comment]
Oops! I'll go fix that now. Thanks for the report.

In case you didn't find them, samples are in the repo under samples/, also they're incorporated throughout the docs at https://squib.readthedocs.io/

**Comment by andymeneely** [comment]
Fixed it by just removing all that other stuff and pointing them to the docs. Much simpler.
