### ISSUE TITLE
Feature Idea: Squib::Deck.new yields an object that can be asked for data

### ISSUE THREAD

**Issue by infews** [andymeneely/squib#313]
I find this project fascinating. And I'm using it exactly as intended - to prototype a card game.

However, as a Rubyist, I find that I would prefer to build my decks of cards via Ruby composition. This would mean building my own object hierarchy of Ruby classes and then ask each card for its data.

I find this more succinct, descriptive, and easier to work with than having data live in YAML

I'm thinking something like this...

```ruby
Card = Struct.new(:name, :type, :text, :icon) 

roadster = Card.new(
  name: "Roadster",
  type: "Vehicle",
  text: "Supports 2 passengers",
)

sedan = Card.new(
  name: "Sedan",
  type: "Vehicle",
  text: "Supports 4 passengers",
)

minivan = Card.new(
  name: "Minivan",
  type: "Vehicle",
  text: "Supports 7 passengers",
)

 bus = Card.new(
  name: "Bus",
  type: "Vehicle",
  text: "Supports 14 passengers",
)

cards = []
cards << roadster * 10
cards << sedan * 9
cards << minivan * 8
cards <<  bus * 7

Squib::Deck.new cards: cards, layout: 'economy.yaml' do |card|
  text card.title
  # etc
end
```

...and this frees the game designer up to organize their `Card` object hierarchy and composition however they want. In this example, it may make more sense to have a `VehicleCard` class.

I'll add that it makes the implicit `Array` operations explicit, which may be easier for non-Rubyists to follow.

Does this sound interesting? I think it would be a simple add to `Squib::Deck#initialize`[1] if you like.

Thoughts?

[1]: https://github.com/andymeneely/squib/blob/006391245b9bd6046c0fab0f0ec437978eb062c0/lib/squib/deck.rb#L74

**Comment by andymeneely** [comment]
Hm. Interesting. What's confusing to me here is that when defining "a deck", I'm really working with "a card". If every card is the same, then that works out. But it breaks down when some cards are slightly different in some way.

For me, I try to avoid magic numbers in source code and keep the data adjustments. I personally do a lot of spreadsheets as part of handling my data. I personally don't work with game data in a yml file or csv file (my layouts are in yml of course).

The data frame currently defines methods for every column it reads from xlsx/csv/yml anyway, so you can already do `text str: data.title` as it is.

But let's explore this more.

Can you give an example of a `Card` object hierarchy that is more complex?

**Comment by infews** [comment]
Thanks for asking for an example. It's forced me to understand how Squib works even more!

I think we're saying the same thing. It's just a Ruby & OOP style question. 

Here's how I would organize the code from the [Iconography example](https://squib.readthedocs.io/en/v0.15.0/guides/getting-started/part_2_iconography.html) in a more Rubyist style:

```ruby
# I would expect to put the base card in a separate file
class Card

  FACTION_SVG_PARAMS = {
    x: 75,
    y: 75,
    width: 75,
    height: 75
  }

  ILLUSTRATION_SVG_PARAMS = {
    x: 237.5,
    y: 237.5,
    width: 350,
    height: 350
  }

  attr_reader :name, :faction, :power, :illustration

  def initialize(name:, power:, illustration:)
    @name = name
    @power = power
    @illustration = illustration
  end

  def faction_svg
    FACTION_SVG_PARAMS.merge(file: GameIcons.get(@faction_icon).file)
  end
  
  def illustration_svg
    ILLUSTRATION_SVG_PARAMS.merge(file: GameIcons.get(@illustration).file)
  end
end

# I would expect to put each card child class in its own file
class HumanCard < Card
  def initialize(name:, power:, illustration:)
    super
    @faction = :human
    @faction_icon = :backup
  end
end

class DroneCard < Card
  def initialize(name:, power:, illustration:)
    super
    @faction = :drone
    @faction_icon = :auto_repair
  end
end

# I would expect all of this to be in one file
ninja = HumanCard.new(name: "Ninja", power: "Use the power of another player", illustration: :ninja_mask)
pirate = HumanCard.new(name: "Pirate", power: "Steal 1 card from another player", illustration: :pirate_skull)
zombie = DroneCard.new(name: "Zombie", power: "Take a card from the discard pile", illustration: :shambling_zombie)
robot = DroneCard.new(name: "Robot", power: "Draw two cards", illustration: :robot_golem)

cards = []
cards << ninja * 1
cards << pirate * 4
cards << zombie * 10
cards << robot * 10

layouts = ['economy.yml', '_part2_03_illustrations.yml']

Squib::Deck.new cards: cards, layout: layouts do |card|
  # Common
  background color: 'white'
  rect layout: 'cut'
  rect layout: 'safe'
  text str: Time.now, layout: 'credits'
  save_sheet prefix: '_part2_03_illustrations_', columns: 4
  save_pdf trim: 37.5

  # Card-specific
  text str: card.name, layout: 'title'
  text str: card.power, layout: 'description'
  svg card.faction_svg
  svg card.illustration_svg
end
```
Note: I don't know where the "title" and "description" layouts are, so I left the two `text` calls mostly alone. 

I find this simpler than putting some of the data in Ruby, some in YAML, and some in CSV. Like I said, it's style.

Yes, this is putting literals in code. I don't see these as "magic" values. I see a Squib project has having Cards with data, so put the data with objects they belong to.

I think it would also remove the need for Ruby inside the `Deck.new` block. You wouldn't need to `map` or use ranges to find the correct values. The current card is always in scope and can tell you what it wants.

(I'm sure there are ways to refactor this further. Like with `Layout` modules that get mixed-in to `Card` classes. Or something. I would have to see as I built out the cards for a game.)

So I'm offering to give the developer an option. If the `cards` param is an integer, the code works as today. If it is an array, then iterate over the array and yield each card to the block.

**Comment by andymeneely** [comment]
I think this is an interesting approach. I don't think I'm going to adopt it but I'll keep this style of thinking in mind for future ideas.
