### ISSUE TITLE
How to refer to fonts? Docker issue?

### ISSUE THREAD

**Issue by newobj** [andymeneely/squib#314]
I'm on OSX, running squib via Docker.

I'm using the 'better' example and just trying to change the font. I have a system font called Glubby. I've tried the following:

       color: '#F3EFE3', font: 'Glubby, 32',

       color: '#F3EFE3', font: 'Glubby BOLD, 32',

       color: '#F3EFE3', font: 'Glubby, BOLD, 32',

None of them work.

Per Font Book, here is Glubby's information:

	PostScript name	Glubby-BOLD
	Full name	Glubby BOLD
	Family	Glubby
	Style	BOLD

How do I properly refer to the font? Is this not going to work in general on account of Docker?

**Comment by andymeneely** [comment]
You'll need to install the fonts to the image yourself. So you'll need your own Dockerfile that starts from Squib's and then install the fonts. Here's how I do it ([taken from here](https://github.com/andymeneely/victory-point-salad/blob/master/Dockerfile)

```Dockerfile
FROM andymeneely/squib:latest

RUN mkdir ~/.fonts
COPY fonts/*.otf /usr/share/fonts/
COPY fonts/*.ttf /usr/share/fonts/
RUN fc-cache -f -v /usr/share/fonts/

WORKDIR /usr/src/app
```

So I keep the font files locally, then copy them over to the image to where `fc-cache` looks, run `fc-cache` to install.

Unfortunately Pango doesn't support fonts not installed on your system. It's in their backlog but they don't seem motivated to support it.
