### ISSUE TITLE
Wrong unit conversion

### ISSUE THREAD

**Issue by VitalyVaryvdin** [andymeneely/squib#315]
Defining deck as follows: 
`Squib::Deck.new  width: '60mm', height: '114mm', cards: data['name'].size, layout: layouts do`
Sprue is 
`sheet_width: 210mm
sheet_height: 297mm
card_width: 60.0mm
card_height: 114.0mm`

Upon printing to pdf sizes are totally different - much smaller. Can you tell me where shall i dig?

**Comment by andymeneely** [comment]
Do you specify the sprue in your `save_pdf` call?

**Comment by VitalyVaryvdin** [comment]
I did.
After playing with it for quite a bit of time managed to achieve what I needed. The issue was related to cut_zone and similar. Sorry for opening an issue before I ever properly tried Squib out.
