### ISSUE TITLE
More flexible save_png names

### ISSUE THREAD

**Issue by nickolasreynolds** [andymeneely/squib#340]
It would be nice if you could simply specify a filename for save_png rather than having to muck about with prefix, suffix, and the (apparently un-disable-able) count_format.

I'm having to write a separate script to post-process the names that Squib outputs because I can't get Squib to just let me do what I want to do (which is to simply save each PNG with the card's name, without any count number attached.)

There is also inconsistent behavior with the existing functionality, for example I can successfully specify `save_png prefix: deck['Name']` and my output looks like FirstCardName00.png SecondCardName01.png etc.

But `save_png suffix: deck['Name']` doesn't work at all, it just outputs Card_00.png Card_01.png etc. And, again, there's no way to disable the annoying numbers!

There also doesn't seem to be a way to programmatically build up a more complicated string. Attempting to do so, e.g. `'prefix' + deck['Name'] + 'suffix'` results in an error: "no implicit conversion of Array into String".

As with almost every other Squib function, I find myself being forced to manually unroll the "think in arrays" paradigm in order to get anything done:

```
d[NAME].each.with_index do |name, i|
unless name.nil?

    save_png
        prefix: 'N' + format('%03d', i.to_s)[-3..-1] + '_' + d[NAME][i],
        count_format: '',
        range: i

end # unless name.nil?
end # d[NAME].each.with_index do |name, i|
```

**Comment by nickolasreynolds** [comment]
On my end, `save_png prefix: d[NAME]` outputs AnActualCardName00.png, AnotherActualCardName01.png, etc. `save_png suffix: d[NAME]` outputs card_00.png, card_01.png, etc.

For most elements on my cards, I format things based on the unique content of the card itself. For example, most text elements have dynamically sized text so that it stays within the  bounds of various background graphical elements.

Another example is that within the primary textbox, the formatting and centering change based on whether the card has rules text or flavortext or neither or both, and how long each is.

Another example is that I keep a list of the graphical extents of every element rendered on every card, so that I can "hint" literally everything if I want to, for debugging positioning issues and the like. (This bookkeeping is also necessary to dynamically position elements relative to one another.)

As I interpret the concept, the "thinking in arrays" approach would be to simply define a chain of logic and then feed it the data array representing the deck. (Maybe I'm just naive or misinterpret what "thinking in arrays" is supposed to mean.)

And that's actually what the original version of my rendering script looked like. But as I slowly complexified the functionality to render things that were closer to actual cards and not just simple mockups, and to make the script usable for people other than myself, almost every single rendered element in my script changed from something like 

```
	png		file:		d[ART],
			x:		art_box.x1,
			y:		art_box.y1,
			width:		art_box.w,
			height:		art_box.h,
```

to something like

```
d[ART].each.with_index do |art, i|

    temp = nil

	if art.nil? and d[NAME][i]
	
		# Is the data file missing art for this card?
		# Try guessing NAME.png
	
		temp = "#{d[NAME][i]}.png"
		
	else
	
		temp = art
	
	end
    
	unless temp.nil?

        if not File.exist?(ART_PATH + temp) then next end

	png		file:		ART_PATH + temp,
			x:		art_box.x1,
			y:		art_box.y1,
			width:		art_box.w,
			height:		art_box.h,
			range:		i
				
	end

end # d[ART].each.with_index do |art, i|
```

so that in the end I'm using Squib as little more than a wrapper for some Cairo and Pango functions.

**Comment by nickolasreynolds** [comment]
Things like xywh really can't be put in a data table, they're determined separately and dynamically for every element on every card, based on the disposition of previous elements.

I use the data table is for the contents of the cards, not the results of a long chain of formatting logic. (Besides, if I stored all the xywh information the data table, I'd add like 200 columns to the data table ...)

Keeping a hardcoded table of all of that information would also make changing a layout virtually impossible. As it stands right now, I can simply adjust the position of, say, the title bar, and every element on the title bar on every card (that has a title bar) automatically realigns with it, and everything positioned relative to the title bar automatically realigns with it, and everything positioned relative to any of those things automatically realign with them, etc., because the xywh of those elements refer to the xywh of their relevant "parents", not to numbers in a table.

Want to change the height or width of the entire card template? Edit a single number, and every other element on every card is automatically repositioned, no further editing is needed, everything just works. Data tables can't do that, even if I thought keeping 200 position coordinates in my card data table was reasonable.

**Comment by andymeneely** [comment]
Sounds complicated. I mean, a spreadsheet can do math for you and update dependencies... but I get what you're saying.

If every card is really so different, then maybe it's time to just have separate image files and do it traditionally without automation. It sounds like you're running into this phenomenon: https://xkcd.com/1319/

I can see how the organization of a card might change if things all depend on each other. But I also wonder... don't players expect consistency? If icons are in different places depending on subtle factors then I imagine players would have trouble usability-wise. 

I don't know. Just my two cents.

FWIW, tonight I implemented a `placeholder` feature and `img_missing` option. It's in my dev branch if you want to play with it. Once I get a chance to test it out on my projects I'll release it to v0.18. 

Anyway, FWIW I think I've answered your original question and given you all the tools you need. I'm closing this now. Best of luck!
