### ISSUE TITLE
Circle drawing stroke from current x,y to circle origin?

### ISSUE THREAD

**Issue by ryanabrams** [andymeneely/squib#35]
Whenever I use a circle command in my decks, a stroke is drawn from the closing coordinates of the prior command to the origin coordinates of the circle, then the circle itself is drawn. The only way I have found to work around it is to draw a circle with no stroke, then re-draw the same circle with a stroke at the same coordinates.

I'm not sure if this is an issue with Squib or an upstream Cairo issue, but looking in lib/squib/graphics/shapes.rb, and with the context that I have absolutely no idea how cairo works, it looks like a simple
```
cc.move_to(x,y)
```
at the start of the circle function would probably address it, though it might also need a stroke width set to 0 first (depending on how move_to works)

Thanks!

**Comment by andymeneely** [comment]
Ah, you're right. Weird. None of the other shapes seem to have that issue. `cc.move_to(x,y)` fixes it though. 

I'm also surprised it's not part of my save/restore cycle. 

I'll push the fix into the next release, which is going to be soon.
