### ISSUE TITLE
Google Sheets support

### ISSUE THREAD

**Issue by LouisDeconinck** [andymeneely/squib#353]
It would be nice to import data from Google Sheets automatically.

I followed these examples:
https://github.com/andymeneely/squib/wiki/Automatic-Google-Sheets-CSV-Export and https://github.com/andymeneely/squib/issues/164

But none of them worked, I get the following error:
```
deck.rb:5:in `initialize': Invalid argument @ rb_sysopen - GOOGLESHEETSLINK (Errno::EINVAL)
        from deck.rb:5:in `open'
        from deck.rb:5:in `<main>'
```

**Comment by andymeneely** [comment]
See #164, also https://github.com/andymeneely/squib/discussions/350
