### ISSUE TITLE
Smart Quotes: convert to curly quotes at word boundaries

### ISSUE THREAD

**Issue by andymeneely** [andymeneely/squib#50]
See [Wikipedia](http://en.wikipedia.org/wiki/Quotation_mark) article that mentions smart quoting.

Basically, use the curly quotes according to word boundaries so that quotes curl inward. As opposed to being perfectly vertical. 

Not sure if smart quotes are handled by Pango or not, but these would be nice to have. Might be as simple as doing a string-replace (assuming UTF-8 strings). Shouldn't vary from font-to-font. Pango does handle word boundaries, so I could use that.

What if the font doesn't have curly quotes? Is there a way of checking that? Or just fail gracefully?

**Comment by pickfifteen** [comment]
Here are the issues I see in 674397c: 

* Causes crash if `markup: true` and a tag with quotes in it is in the text.
* Does not process single-quotes (for quotes within quotes) or apostrophes.
* If single quotes and apostrophes were processed with the same logic as double-quotes now, apostrophes would be backwards.

Perhaps a library like [RubyPants](https://github.com/jmcnevin/rubypants) would be useful, whether to partially use for implementation or simply to take ideas and test cases from. (The em-dash and ellipsis replacements they do would be handy here as well.)

**Comment by andymeneely** [comment]
Ok, try out that one. I got rid of the `quotes` options and just combined it with `markup: true`. My logic isn't as complex as RubyPants, but it's pretty close. 

One thing I don't have yet is the ability to configure custom characters. I'll do that in the configuration file. 

  - [ ] Allow configurable characters in `config.yml`

**Comment by pickfifteen** [comment]
Only one problem: Currently doesn't work if embeds exist. Looks like just need to set the ```str``` in the ```if markup``` block, since the ```layout.markup``` gets reset in the embed process. Other than that, everything appears as expected in my tests, fantastic.

**Comment by andymeneely** [comment]
Great! Fixed that in 211e7c13b3e7955690f65f0b43ecb2943dfd0393.

Once I do the config thing I'll release the next gem.

**Comment by andymeneely** [comment]
Got this wrapped up in 0e22c52b0f39e6105b34f8ad088e9dfea1b6effc and 063d5156d6945e1b8c70a8fe7ad438f1ab04465f
