### ISSUE TITLE
Arrays (with singleton expansion) for embed parameters

### ISSUE THREAD

**Issue by pickfifteen** [andymeneely/squib#54]
Being able to pass the embed commands arrays would be great. A regular case will be correlating the size of the icon to the size of the font for a particular card. The parameters I need to pass as arrays for my current project are width, height, and dy.

**Comment by andymeneely** [comment]
Definitely can be done. I figured I'd do this after the issues with #30 are resolved. I'll probably put singleton expansion on all the parameters except `key`.

**Comment by andymeneely** [comment]
In working on this, I think I'm going to push this into a later milestone. I'd like to refactor how Squib handles processing arguments to be a little more robust, and this will be much simpler once that's done.

**Comment by andymeneely** [comment]
@pickfifteen I believe I have this working - it's in the master branch and slated for the next release. But would love your testing and input!

**Comment by pickfifteen** [comment]
I was able to uncomment my code I wrote months ago in anticipation of having this feature and it worked like a charm. :) Thanks!

**Comment by andymeneely** [comment]
Brilliant! I love it when a plan comes together.
