### ISSUE TITLE
Multi-byte characters before embeds cause them to be improperly placed

### ISSUE THREAD

**Issue by pickfifteen** [andymeneely/squib#57]
A multi-byte character, like the em-dash, appearing before an embed causes it to be improperly placed. ```layout.index_to_pos``` expects a byte index.

This may be as easily fixed as changing line 122 of text.rb to ```index = clean_str.b.index(key)```, but I haven't and can't currently check whether this causes issues if the key itself has multi-byte characters.

**Comment by andymeneely** [comment]
Should be fixed now?

**Comment by pickfifteen** [comment]
Fixed for my problem cases, yup.
