### ISSUE TITLE
Add ability to use 'gray' instead of 'subpixel' antialiasing for text

### ISSUE THREAD

**Issue by pickfifteen** [andymeneely/squib#58]
Rendering text uses subpixel antialiasing. This can be easily seen by simply placing white text on a transparent background; zoom in and you can see the colored artifacts. When preparing files for printing rather than screen view, or for later integration into other images, this is not desired.

Changing the config antialiasing does not affect this. Also, I was not able to discover any way to modify the project to implement this change.

**Comment by andymeneely** [comment]
Ah - so font rendering, including antialiasing, is handled by a different set of options in Cairo/Pango. (Technically, we give Cairo options to Pango, who then passes it back to Cairo). They also default to subpixel. I haven't yet opened those options up to Squib. 

I'm pretty close to a working solution. I'll get it pushed soon. I'll warn you - the text doesn't look as good on my screen with the 'gray' option, but I'll take a look at how it prints. There's a couple of other font options to expose too: http://cairographics.org/manual/cairo-cairo-font-options-t.html

**Comment by andymeneely** [comment]
By the way, this is an entertaining thread on the subject. http://lists.cairographics.org/archives/cairo/2006-January/005929.html

**Comment by andymeneely** [comment]
Forgot to close this. It's in 0.5.1
