### ISSUE TITLE
can't install squib

### ISSUE THREAD

**Issue by lgrains** [andymeneely/squib#81]
I'm going around in circles trying to install squib.  Here is a gist of my installation attempt: https://gist.github.com/lgrains/6d964fb775cc2694fe9e.

When I try to install librsvg I get these errors: https://gist.github.com/lgrains/e6c660bed68dfe1862a2

I have run `brew update` successfully.  Any suggestions?

**Comment by lgrains** [comment]
Changing permissions on my /usr/local/var/ directory solved the problem.

**Comment by andymeneely** [comment]
Glad you got it!

**Comment by lgrains** [comment]
@andymeneely Now I'm not so sure.  While everything seemed to be installed, when I do `squib new my_game`  I get the error:  `-bash: squib: command not found`

**Comment by RyPeck** [comment]
@lgrains Is your shell PATH configured to search where your gem's are installed?

**Comment by lgrains** [comment]
I assume so, as I've never had problems finding other gems in my development environment. Any way to check?

I tried both `gem install squib` and creating a Gemfile and running bundle. Here's the resulting Gemfile.lock:

```
GEM
  specs:
    cairo (1.14.1)
      pkg-config (>= 1.1.5)
    gdk_pixbuf2 (2.2.5)
      glib2 (= 2.2.5)
    glib2 (2.2.5)
      pkg-config
    mercenary (0.3.5)
    mini_portile (0.6.2)
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    pango (2.2.5)
      cairo (>= 1.14.0)
      glib2 (= 2.2.5)
    pkg-config (1.1.6)
    roo (2.0.1)
      nokogiri (~> 1)
      rubyzip (~> 1.1, < 2.0.0)
    rsvg2 (2.2.5)
      cairo (>= 1.12.8)
      gdk_pixbuf2 (= 2.2.5)
    ruby-progressbar (1.7.5)
    rubyzip (1.1.7)
    squib (0.6.0)
      cairo (~> 1.14.0)
      mercenary (~> 0.3.4)
      pango (~> 2.2.0)
      roo (~> 2.0.0)
      rsvg2 (~> 2.2.0)
      ruby-progressbar (~> 1.6)

PLATFORMS
  ruby

DEPENDENCIES
  squib
```

**Comment by lgrains** [comment]
Here's my GEM Paths:

```
- GEM PATHS:
     - /Users/louiserains/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0
     - /Users/louiserains/.gem/ruby/2.2.0
```

**Comment by lgrains** [comment]
Further, when I go into `/Users/louiserains/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/`, I see

`drwxr-xr-x   19 louiserains  staff    646 Jun 30 10:03 squib-0.6.0`

**Comment by andymeneely** [comment]
The `which squib` isn't right - it should point to something like (and I'm extrapolating here):
```
/Users/louiserains/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bin
```

The PATH variable needs to be set to point to that, which isn't usually messed with by RubyGems. For example, on my Linux machine I have my `.bashrc` set like this:

```
export PATH="$PATH:$HOME/.gems/bin"
```

GEM Paths is used for storing the actual gems, but then the executable is in that bin folder. This page on RubyGems might help: http://guides.rubygems.org/faqs/#user-install

Either way, `squib new` is just there for convenience and isn't critical to getting started. You'll still be able to do `require squib` in a Ruby file and get going.

**Comment by spdustin** [comment]
@lgrains, can you try `rbenv rehash` then `rbenv which squib` and post back? I use rbenv also, and have no issues, but I may be able to help you debug.

**Comment by lgrains** [comment]
I was experiencing an out of memory error on use_cairo, so I bumped my Ruby version up to 2.2.2 based on a post about halfway down here:  https://boardgamegeek.com/thread/1293453/introducing-squib-ruby-gem-prototyping-games-v060/page/2

Next, I got an error about Cairo::Color, which I resolved by putting 

```
require "cairo"
require "pango"
require "nokogiri"
require "squib"
```
at the top of my deck.rb file.  I can now run the examples and can create my own deck too!

**Comment by andymeneely** [comment]
Any chance you could post the error when disabling those requires? You probably don't need the first three. Definitely the third ;)

**Comment by lgrains** [comment]
```
ruby deck.rb
/Users/louiserains/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require': uninitialized constant Cairo::Color (NameError)
	from /Users/louiserains/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/louiserains/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/squib-0.6.0/lib/squib.rb:2:in `<top (required)>'
	from /Users/louiserains/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /Users/louiserains/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /Users/louiserains/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from deck.rb:4:in `<main>'
```

**Comment by zaphod46** [comment]
I can confirm observing the same behavior as lgrains and the same fix works for me. Version info:

$ ruby --version
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]

$ brew info cairo pango
cairo: stable 1.14.2 (bottled)
Vector graphics library with cross-device output support
http://cairographics.org/
/usr/local/Cellar/cairo/1.14.2_1 (111 files, 6.1M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/cairo.rb

pango: stable 1.36.8 (bottled), HEAD
Framework for layout and rendering of i18n text
http://www.pango.org/
/usr/local/Cellar/pango/1.36.8_2 (126 files, 4.7M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/pango.rb

**Comment by andymeneely** [comment]
This baffles me because the very first thing I do when someone does a `require 'squib'` is to do those other requires on cairo, pango, and roo (which in turn requires nokogiri). 

https://github.com/andymeneely/squib/blob/master/lib/squib.rb

**Comment by ryanabrams** [comment]
This is related to a regression in rubygems in ruby 2.2.0. https://github.com/rubygems/rubygems/issues/784

Just upgrade your rubygems via gem update --system, and it should start working without all the extra requires.

**Comment by rpond-pa** [comment]
Thanks @ryanabrams.  That was indeed the fix I needed to get my `squib` install working and happy.
