### ISSUE TITLE
Add a custom method

### ISSUE THREAD

**Issue by gampleman** [andymeneely/squib#90]
For my game having a custom method would be very handy for this case:

Name | Resilience | Actions
---------|---------------|------------
Operation | - | 1
Silo | 2 | 2

Resilience should render like a brown number in front of a house icon, but not all cards have a resilience (this can probably be achieved already). But actions should be rendered as a number of orange arrows that corresponds to the actions number.

**Comment by andymeneely** [comment]
Given that it's good ol' ruby, you can always define your own methods ;)

There are a couple of ways to handle this already. The first is to do it with ranges. Select the indices of the Actions array with, say, 2, then draw two arrows. Define a method to draw an arbitrary number of arrows how you like, and then loop from 1 to the maximum number of actions and call that method. Here's what I cooked up, and there probably are even cleaner ways to do it:

```ruby
require 'squib'
require 'game_icons'
# Using game_icons for convenience, but you can use whatever images you like

data = {
  'Name'       => %w(Operation Silo),
  'Resilience' => [nil, 1],
  'Action'     => [1, 2],
}

Squib::Deck.new(cards: 2) do

  def draw_arrows(n, range)
    1.upto(n) do |i|
      arrow_svg = GameIcons.get('clockwise-rotation').string
      svg range: range, x: i*110, data: arrow_svg, width: 100, height: 100
    end
  end

  1.upto(2).each do |actions| #for each action count
    # give me the indices to the array that correspond to a "2"
    range = data['Action'].each_index.select {|i| data['Action'][i] == actions}
    draw_arrows actions, range
  end

  save_png
end
```

As you progress from prototypes to more professional-looking cards, you might find that grouping the symbols in a custom way might help the graphic design (such as the way pips are arranged on a die), for that you'll want separate image files and have something like this:

```ruby
svg file: data['Actions'].map { |n| "#{n}_actions.svg" }
# for the original table, the above expression evaluates to ['1_actions.svg','2_actions.svg']
```


My `ranges.rb` sample might be a helpful reference point: https://github.com/andymeneely/squib/blob/master/samples/ranges.rb

**Comment by gampleman** [comment]
I actually ended up using the embed system for this:

```ruby
data['Cost'] = data['Action Cost'].zip(data['Card Cost']).map do |ac, cc|
  ':action:' * ac.to_i + ":card#{cc}:"
end

Squib::Deck.new(cards: data['Name'].length, layout: 'layout.yml') do
  background color: 'white'
  text str: data['Name'], layout: :title
  text str: data['Cost'], layout: :cost do |embed|
    embed.svg key: ':action:', file: 'assets/Action.svg'
    embed.svg key: ":card1:", file: "assets/Card 1.svg"
    embed.svg key: ":card2:", file: "assets/Card 2.svg"
    embed.svg key: ":card3:", file: "assets/Card 3.svg"
    embed.svg key: ":card4:", file: "assets/Card 4.svg"
  end
  save format: :png
end
```

**Comment by andymeneely** [comment]
That works too! Interesting use of `zip` and `map`. I'll document that on the README.
