### ISSUE TITLE
Allow a :scale option to png and svg that scales width/height to keep aspect ratio

### ISSUE THREAD

**Issue by andymeneely** [andymeneely/squib#91]
It would be nice to scale pngs and svgs based on their native widths. If you specify a number for width or height, then `:scale` for the other, then the image should be rendered according to its aspect ratio. 

Here's some cases:

```ruby
# assume foo.png is 100x200
png file: 'foo.png', width: 50, height: :scale # renders at 50x100
png file: 'foo.png', width: :scale, height: 100 # renders at 50x100
png file: 'foo.png', width: :scale, height: :scale # raises an error, or maybe switches to :native?
```

**Comment by court-jus** [comment]
:+1:

**Comment by andymeneely** [comment]
Have you gotten a chance to test it? It's in the master branch now.

**Comment by court-jus** [comment]
No, not yet :)
