### ISSUE TITLE
Card backsides

### ISSUE THREAD

**Issue by gampleman** [andymeneely/squib#93]
Is there a way to specify what to draw on the other surface of a physical card? This would make sense mostly for getting a correct layout in the PDF for two sided printing (though there are quite a few games that rely on using both sides of a card).

**Comment by andymeneely** [comment]
Ok, here's what you can do now, although I've been thinking about ways to make `save_pdf` support this better. 

What I currently do for my games is:
  * For prototyping I print to regular paper on separate sheets. Put in sleeves that also have a piece of cardstock in them to give the cards. That means you make two separate `Squib::Deck` calls, but still from the same Excel sheet. 
  * For nicer prototypes I use TheGameCrafter, which means I just make my backs separately (e.g. in Gimp) and upload them without using Squib. But I also don't usually have tons of different backs in my games yet, so this approach may get tedious. 

If you want to print to paper double-sided, `save_pdf` does give you control over `margin` and `gap`, so you can print two separate pdfs. Just run the paper through the printer again, making sure you get the right margins and orientation. I have not done this, but it's technically feasible. 

But, I don't have anything that would work, say, for duplex printing where we interleave the pages and let the printer reverse it. 

Or there's another situation whee you have cards line up along their bottoms (i.e. top row of cards are fronts, bottom row of cards are upside down backs) so you can fold them in the middle. You *could* create a *third* `Squib::Deck` that takes the output of a prior `Squib::Deck`s and arranges them yourself on a "card" that's 8.5x11, rotating along the bottom. Technically feasible, but kinda yucky.

Eventually I'd like to make `save_pdf` handle multiple `Squib::Deck` classes, and then arrange them in a variety of ways to support these other workflows. The code for `save_pdf` now certainly can be generalized. Something like this is what I envision:

```ruby
fronts = Squib::Deck.new do
  # make your fronts here
end

backs = Squib::Deck.new do
 # make your backs here
end

Squib.save_pdf(decks: [fronts, backs], method: :duplex) # front page, then back page
``` 
Or, perhaps have Squib be aware of what's front and what's back. Something like a ubiquitous argument `face: :front`, (and then always default to `:front`). What I don't like about this approach is (a)introducing a new option *everywhere* is annoying, (b) it can make your builds slower. 

For me, the cleanest option is to create separate Ruby files, e.g. `fronts.rb` and `backs.rb`, then have my `Rakefile` look like this:

```ruby
task default: [:fronts]

task :fronts { load 'fronts.rb' }
task :backs { load 'fronts.rb' }
task :all => [:fronts, :backs]
```

Given that there already is a physical process for handling fronts and backs with separate PDFs, though, and given how complex it will be to properly handle things like duplex printing and interleaving cards, this idea has been low priority for me.

But, in the short term, I should document some these ideas in the README, 
  - [ ] Document some of these ideas in the README
  - [ ] Make a sample or two about backs

**Comment by zaphod46** [comment]
I've written a simple python script for taking directories full of fronts
and backs and making the proper duplex-ready PDFs. It's just one commented
file, but if it helps, please feel free to use it:

https://bitbucket.org/strangelandgames/svg-scripts/overview

Jeff

**Comment by andymeneely** [comment]
Thanks Jeff! Looks like your script calls `pdftk` at the end to do the duplexing. That would work, too - just use a command-line tool.

**Comment by gampleman** [comment]
> Something like a ubiquitous argument face: :front, (and then always default to :front). What I don't like about this approach is (a)introducing a new option everywhere is annoying, (b) it can make your builds slower.

You could introduce a method in the dsl that would look like this:

```ruby
Squib::Deck.new do
  # frontface code here
  backface do
    # backface code here
  end
end
```

**Comment by andymeneely** [comment]
Oh that's an interesting idea. Let me think on that one.

**Comment by andymeneely** [comment]
I'm still thinking about this one. I'm leaning toward this syntax. I'm also looking at clever ways of using Rake to help maintain both a black-and-white version and a color version. I'm wondering if this idea could help with that too.

**Comment by andymeneely** [comment]
I'm open to this syntax - although it's a deep change design-wise because Deck's would now be (potentially) maintaining twice as much data as before. And then there's the huge memory footprint issue. Once we get better `save_sheet` features for #126, I'll circle back to this.

**Comment by Kilian** [comment]
+1 for this ticket and the `backface do` syntax :)

**Comment by andymeneely** [comment]
Yeah I've decided against doing this, and I do it a different way. 

Cons:
  * It basically doubles the size of your Squib code. I prefer to organize the faces into different `Squib::Deck`
  * Creating a second back would double the amount of memory used, and Squib is already a memory hog.
  
What I do instead is use the output of one Squib script into another, and then connect them with my Rakefile. So each script generates different types of card faces, then you can use a separate script to stitch them together however you need. You can see how I do this over at my [Project Bolt Rats](https://github.com/andymeneely/project-bolt-rats) prototype.

I'm still working on better tools to support duplex printing and stuff, but you can accomplish what you need with what you have.

I'm closing the `backface` idea.
