### ISSUE TITLE
Values for spacing on text changed, seem extreme

### ISSUE THREAD

**Issue by pickfifteen** [andymeneely/squib#98]
Sometime between v0.5.1 and now, something occurred to change what the values of text's `spacing` produce. I now need to use a value of -0.012 to achieve what I used to get with a value of -12. Not sure if this change was intended?

**Comment by andymeneely** [comment]
Interesting. I haven't noticed anything on my end. Could be updates to the way fonts are rendered, which would be at your OS level. What font?

**Comment by pickfifteen** [comment]
I'm experiencing the change on both Windows and on Linux. When I set my Gemfile to 0.6.0 the old values work. The font is 'Gentium Book Basic 56'.

**Comment by andymeneely** [comment]
Yup - I broke it (and forgot to regression test it). It was off by a factor 1024. Should be fixed in 9d475995e804d71375d9008d24529fe2c1b669f9
